### ISSUE TITLE
Error: Could not find or load main class org.apache.nutch.indexer.Indexer

### ISSUE THREAD

**Issue by sreelakshmiRajula** [intel-hadoop/HiBench#101]
Hi 
I am trying to run nutch indexing. And I receive the error

"Error: Could not find or load main class org.apache.nutch.indexer.Indexer". 

Please help me in resolving this issue.

**Comment by lvsoft** [comment]
Have you executed `bin/build-all.sh` before running nutch indexing?

**Comment by sreelakshmiRajula** [comment]
Hi,

Thank you for the reply. I have built it and Now it is working fine.
 As you told the job file was missing earlier.
I am able to prepare the data and run indexing task with default settings. (for 100000 files).
When I increase the number of files (500000),  I get the below exception after map 100% and reduce 100% during data generation.

"
INFO mapreduce.Job: Task Id : attempt_1433933150974_0002_r_000037_0, Status : FAILED
Error: org.apache.hadoop.ipc.RemoteException(org.apache.hadoop.hdfs.server.namenode.LeaseExpiredException): No lease on /HiBench/Nutch/Input/segments/20150610161806/parse_data/part-00037/data (inode 17335): File does not exist. Holder DFSClient_attempt_1433933150974_0002_r_000037_0_2104661429_1 does not have any open files. "

Thanks in advance.

**Comment by sreelakshmiRajula** [comment]
Yes I did it. Now it is working fine with default settings. 
Thank you.

**Comment by lvsoft** [comment]
OK, I'll close this issue.

**Comment by gaohannk** [comment]
@sreelakshmiRajula  Could you tell me how to solve this problem? I also encounter it. I build successfully.

**Comment by sreelakshmiRajula** [comment]
as lvsoft told, may be you can try to install nutch properly. In my case, I had nutch setup on some other PC, from there I have copied nutch-1.2.job file to the problematic setup. And after that test ran successfully. And everytime I run indexing task, I see the job file getting updated. May be this is a workaround. Please post here, if you can solve your problem.

**Comment by gaohannk** [comment]
I download nutch 1.1 version from apache and using the same option as in Hibench shell. and I got 
/home/hadoop/HiBench-master/report/nutchindexing/mapreduce/nutch_release/bin/nutch: line 16: .: filename argument required
.: usage: . filename [arguments]
/home/hadoop/HiBench-master/report/nutchindexing/mapreduce/nutch_release/bin/nutch: line 150: classpath: command not found
Error: Could not find or load main class org.apache.hadoop.util.PlatformName


i also find there is a nutch1.2 version in  Hibench. Can I usr that version?

**Comment by sreelakshmiRajula** [comment]
May be you can give a try with nutch-1.2. Earlier somebody has suggested me to use nutch-1.2 ( I forgot exactly in which forum it was suggested.) And I am not sure about this error "Error: Could not find or load main class org.apache.hadoop.util.PlatformName".
May be you can try following the steps to build nutch. 
And under "\HiBench\common\hibench\nutchindexing\target\nutch-1.2\" folder, I have nutch-1.2.job, nutch-1.2.jar and nutch-1.2.war three files. And we require all these files for running indexing Job.
