### ISSUE TITLE
Syntax error and unbound variable

### ISSUE THREAD

**Issue by redaaz** [intel-hadoop/HiBench#104]
Hi,
I'm trying to run HiBench- Sort task on localhost. I do not understand what happens at last (below)? and why does it throw such errors?  

thanks.

/Users/reda/Documents/HiBench-master/workloads/sort/spark/java/bin/run.sh
Parsing conf: /Users/reda/Documents/HiBench-master/conf/00-default-properties.conf
Parsing conf: /Users/reda/Documents/HiBench-master/conf/10-data-scale-profile.conf
Parsing conf: /Users/reda/Documents/HiBench-master/conf/99-user_defined_properties.conf
Parsing conf: /Users/reda/Documents/HiBench-master/workloads/sort/conf/00-sort-default.conf
Parsing conf: /Users/reda/Documents/HiBench-master/workloads/sort/conf/10-sort-userdefine.conf
Parsing conf: /Users/reda/Documents/HiBench-master/workloads/sort/spark/java/java.conf
\e[1;32mstart \e[0m\e[4;32mJavaSparkSort\e[0m \e[1;32mbench\e[0m
\e[1;36mhdfs rm -r: \e[0;36m/usr/local/Cellar/hadoop/2.6.0/libexec/bin/hadoop --config /usr/local/Cellar/hadoop/2.6.0/libexec/etc/hadoop fs -rm -r -skipTrash hdfs://localhost:9000/HiBench/Sort/Output\e[0m
15/06/11 18:08:34 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Deleted hdfs://localhost:9000/HiBench/Sort/Output
\e[1;35mhdfs du -s: \e[0;35m/usr/local/Cellar/hadoop/2.6.0/libexec/bin/hadoop --config /usr/local/Cellar/hadoop/2.6.0/libexec/etc/hadoop fs -du -s hdfs://localhost:9000/HiBench/Sort/Input\e[0m
15/06/11 18:08:35 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
expr: not a decimal number: 'N'
expr: syntax error
\e[1;36mExport env: \e[0;36mSPARKBENCH_PROPERTIES_FILES\e[1;36m=\e[0;36m/Users/reda/Documents/HiBench-master/report/sort/spark/java/conf/sparkbench/sparkbench.conf\e[0m
\e[1;32mSubmit Spark job: \e[0;32m/Users/reda/spark-1.3.1-bin-hadoop2.6/bin/spark-submit  --properties-file /Users/reda/Documents/HiBench-master/report/sort/spark/java/conf/sparkbench/spark.conf --class com.intel.sparkbench.sort.JavaSort --master local[4]  /Users/reda/Documents/HiBench-master/src/sparkbench/target/sparkbench-4.0-SNAPSHOT-MR2-spark1.3-jar-with-dependencies.jar hdfs://localhost:9000/HiBench/Sort/Input hdfs://localhost:9000/HiBench/Sort/Output\e[0m
15/06/11 18:08:37 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
15/06/11 18:08:40 INFO remote.RemoteActorRefProvider$RemotingTerminator: Remoting shut down.
/Users/reda/Documents/HiBench-master/bin/functions/workload-functions.sh: line 65: kill: (8930) - No such process
expr: not a decimal number: 'N'
expr: syntax error
/Users/reda/Documents/HiBench-master/bin/functions/workload-functions.sh: line 75: $2: unbound variable

**Comment by lvsoft** [comment]
Seems like a weird issue. My guess is, maybe the `date` of your distribution is different with typical Linux distribution. I'll explain the detail:

According to your log, `expr` reported a syntax error and interrupted the function, which cause the unbound variable error. In HiBench, the only place contains `expr` is in `bin/functions/workload-functions.sh`, `function timestamp`, which is used to get current timestamp.

It'll get seconds and nano seconds by `date +%s` and `date +%N` and calculate the float point value of current timestamp. In typical Linux distributions, `date` is a part of GNU coreutils, for example:

        $ date --version       
        date (GNU coreutils) 8.21
        Copyright (C) 2013 Free Software Foundation, Inc.
        License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
        This is free software: you are free to change and redistribute it.
        There is NO WARRANTY, to the extent permitted by law.

        Written by David MacKenzie.

Can you paste the result of your `date --version`, `date +%s` and `date +%N`? This will helps us to improve the compatibility for more distributions. Thanks

**Comment by lvsoft** [comment]
After a further investigation, it seems in some distribution, the gnu coreutils version of date is missing, and will fallback to sh's builtin version, which lack +N option:

         $ date +%s
         1440136790
         
         $ date +%N
         044633140
         
         $ busybox date +%N
         %N
         
         $ busybox date +%s
         1440136803

This should be considered.
