### ISSUE TITLE
sleep program in benchmark.lst errors out

### ISSUE THREAD

**Issue by wingau** [intel-hadoop/HiBench#106]
Running the list of programs in the default HiBench/conf/benchmarks.lst

From HiBench/report/sleep/mapreduce/bench.log

Unknown program 'sleep' chosen.
Valid program names are:
  aggregatewordcount: An Aggregate based map/reduce program that counts the words in the input files.
...

**Comment by lvsoft** [comment]
Can you paste more logs? For example, `report/sleep/**/conf/sleep/sparkbench/sparkbench.conf`.

The `sleep` job has been removed in MR2's hadoop-example, which'll require additional handling. However, HiBench 4.0 should do the auto detection and do the tricks for you.
