### ISSUE TITLE
HDFS ToolRunner warning

### ISSUE THREAD

**Issue by HatY** [intel-hadoop/HiBench#107]
When I run `run_all.sh` script I get the following warning:

`WARN mapreduce.JobSubmitter: Hadoop command-line option parsing not performed. Implement the Tool interface and execute your application with ToolRunner to remedy this`

I am using Ambari-managed Hadoop cluster, with HDP 2.2, HDFS 2.6.

**Comment by lvsoft** [comment]
Since its a warning, did it cause any problems?

**Comment by HatY** [comment]
It seems that command line options are not read and tests use default values.
