### ISSUE TITLE
Error: Found interface org.apache.hadoop.mapreduce.Counter, but class was expected

### ISSUE THREAD

**Issue by gaohannk** [intel-hadoop/HiBench#113]
My environment is Ubuntu 14.04. Hadoop 2.6 . When I run Bayes job, i get the following error. is it the code problem or compile problem. I compile it on MR2.

Parsing conf: /home/hadoop/HiBench-master/conf/00-default-properties.conf
Parsing conf: /home/hadoop/HiBench-master/conf/10-data-scale-profile.conf
Parsing conf: /home/hadoop/HiBench-master/conf/99-user_defined_properties.conf
Parsing conf: /home/hadoop/HiBench-master/workloads/bayes/conf/00-bayes-default.conf
Parsing conf: /home/hadoop/HiBench-master/workloads/bayes/conf/10-bayes-userdefine.conf
start HadoopPrepareBayes bench
hdfs rm -r: /usr/local/hadoop/bin/hadoop --config /usr/local/hadoop/etc/hadoop fs -rm -r -skipTrash hdfs://master:9000/HiBench/Bayes/Input
15/07/10 12:32:15 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
rm: `hdfs://master:9000/HiBench/Bayes/Input': No such file or directory
Submit MapReduce Job: /usr/local/hadoop/bin/hadoop --config /usr/local/hadoop/etc/hadoop jar /home/hadoop/HiBench-master/src/autogen/target/autogen-4.0-SNAPSHOT-jar-with-dependencies.jar HiBench.DataGen -t bayes -b hdfs://master:9000/HiBench/Bayes -n Input -m 24 -r 12 -p 100000 -class 100 -o sequence
15/07/10 12:32:21 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
15/07/10 12:32:28 WARN mapreduce.JobSubmitter: Hadoop command-line option parsing not performed. Implement the Tool interface and execute your application with ToolRunner to remedy this.
15/07/10 12:32:57 INFO HiBench.BayesData: Closing bayes data generator...
finish HadoopPrepareBayes bench
Run bayes/mapreduce
Exec script: /home/hadoop/HiBench-master/workloads/bayes/mapreduce/bin/run.sh
Parsing conf: /home/hadoop/HiBench-master/conf/00-default-properties.conf
Parsing conf: /home/hadoop/HiBench-master/conf/10-data-scale-profile.conf
Parsing conf: /home/hadoop/HiBench-master/conf/99-user_defined_properties.conf
Parsing conf: /home/hadoop/HiBench-master/workloads/bayes/conf/00-bayes-default.conf
Parsing conf: /home/hadoop/HiBench-master/workloads/bayes/conf/10-bayes-userdefine.conf
Parsing conf: /home/hadoop/HiBench-master/workloads/bayes/mapreduce/hadoop.conf
start HadoopBayes bench
Export env: HADOOP_EXECUTABLE=/usr/local/hadoop/bin/hadoop
Export env: HADOOP_HOME=/usr/local/hadoop
Export env: HADOOP_CONF_DIR=/usr/local/hadoop/etc/hadoop
hdfs rm -r: /usr/local/hadoop/bin/hadoop --config /usr/local/hadoop/etc/hadoop fs -rm -r -skipTrash hdfs://master:9000/HiBench/Bayes/Output
15/07/10 12:33:05 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
rm: `hdfs://master:9000/HiBench/Bayes/Output': No such file or directory
hdfs du -s: /usr/local/hadoop/bin/hadoop --config /usr/local/hadoop/etc/hadoop fs -du -s hdfs://master:9000/HiBench/Bayes/Input
15/07/10 12:33:08 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
15/07/10 12:33:14 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Error: Found interface org.apache.hadoop.mapreduce.Counter, but class was expected
Error: Found interface org.apache.hadoop.mapreduce.Counter, but class was expected
Error: Found interface org.apache.hadoop.mapreduce.Counter, but class was expected
Error: Found interface org.apache.hadoop.mapreduce.Counter, but class was expected
Error: Found interface org.apache.hadoop.mapreduce.Counter, but class was expected
Error: Found interface org.apache.hadoop.mapreduce.Counter, but class was expected
Error: Found interface org.apache.hadoop.mapreduce.Counter, but class was expected
Error: Found interface org.apache.hadoop.mapreduce.Counter, but class was expected
Error: Found interface org.apache.hadoop.mapreduce.Counter, but class was expected
Error: Found interface org.apache.hadoop.mapreduce.Counter, but class was expected
Error: Found interface org.apache.hadoop.mapreduce.Counter, but class was expected
Error: Found interface org.apache.hadoop.mapreduce.Counter, but class was expected
Error: Found interface org.apache.hadoop.mapreduce.Counter, but class was expected
Error: Found interface org.apache.hadoop.mapreduce.Counter, but class was expected
Error: Found interface org.apache.hadoop.mapreduce.Counter, but class was expected
Error: Found interface org.apache.hadoop.mapreduce.Counter, but class was expected
Error: Found interface org.apache.hadoop.mapreduce.Counter, but class was expected
Error: Found interface org.apache.hadoop.mapreduce.Counter, but class was expected
Error: Found interface org.apache.hadoop.mapreduce.Counter, but class was expected
Error: Found interface org.apache.hadoop.mapreduce.Counter, but class was expected
Error: Found interface org.apache.hadoop.mapreduce.Counter, but class was expected
Error: Found interface org.apache.hadoop.mapreduce.Counter, but class was expected
Error: Found interface org.apache.hadoop.mapreduce.Counter, but class was expected
Error: Found interface org.apache.hadoop.mapreduce.Counter, but class was expected
Error: Found interface org.apache.hadoop.mapreduce.Counter, but class was expected
Error: Found interface org.apache.hadoop.mapreduce.Counter, but class was expected
Error: Found interface org.apache.hadoop.mapreduce.Counter, but class was expected
Error: Found interface org.apache.hadoop.mapreduce.Counter, but class was expected
Error: Found interface org.apache.hadoop.mapreduce.Counter, but class was expected
Error: Found interface org.apache.hadoop.mapreduce.Counter, but class was expected
Error: Found interface org.apache.hadoop.mapreduce.Counter, but class was expected
Error: Found interface org.apache.hadoop.mapreduce.Counter, but class was expected
Error: Found interface org.apache.hadoop.mapreduce.Counter, but class was expected
Error: Found interface org.apache.hadoop.mapreduce.Counter, but class was expected
Error: Found interface org.apache.hadoop.mapreduce.Counter, but class was expected
Error: Found interface org.apache.hadoop.mapreduce.Counter, but class was expected
Error: Found interface org.apache.hadoop.mapreduce.Counter, but class was expected
Error: Found interface org.apache.hadoop.mapreduce.Counter, but class was expected
Error: Found interface org.apache.hadoop.mapreduce.Counter, but class was expected
Error: Found interface org.apache.hadoop.mapreduce.Counter, but class was expected
Error: Found interface org.apache.hadoop.mapreduce.Counter, but class was expected
Container exited with a non-zero exit code 143
15/07/10 12:34:22 WARN driver.MahoutDriver: No trainnb.props found on classpath, will use command-line arguments only
15/07/10 12:34:23 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Exception in thread "main" java.lang.IncompatibleClassChangeError: Found interface org.apache.hadoop.mapreduce.JobContext, but class was expected
        at org.apache.hadoop.util.RunJar.main(RunJar.java:136)
finish HadoopBayes bench
Run all done!

**Comment by cupdike** [comment]
Sounds like the same issue I just got resolved:
https://github.com/intel-hadoop/HiBench/issues/112

**Comment by gaohannk** [comment]
Yes, it's the mahout problem. download mahout directly and set environment variable can solve this.

**Comment by gaohannk** [comment]
But another problem is the second job(CMD in shell) can't excute. 
 ERROR AbstractJob: Unexpected -el while processing Job-Specific Options:
