### ISSUE TITLE
load-config.py should parse yarn-site.xml for yarn.resourcemanager.hostname

### ISSUE THREAD

**Issue by lexpierce** [intel-hadoop/HiBench#116]
Currently `load-config.py` only parses `yarn-site.xml` for **yarn.resourcemanager.address**. This value is best derived programmatically from **yarn.resourcemanager.hostname**, and the latter should probably be what is being parsed for. Many installation directions (looking at you, Cloudera manual CDH) specify setting the second value.

**Comment by lvsoft** [comment]
Thanks for your advice. I'll refine the code.
