### ISSUE TITLE
workload-functions.sh: line 76: $3: unbound variable

### ISSUE THREAD

**Issue by giagiannis** [intel-hadoop/HiBench#117]
Hello,

I am trying to execute the join workload and I face the following issue. I successfully run prepare/prepare.sh script but when trying to execute mapreduce/bin/run.sh, I am getting the following output:
```
Parsing conf: /root/HiBench/conf/00-default-properties.conf
Parsing conf: /root/HiBench/conf/10-data-scale-profile.conf
Parsing conf: /root/HiBench/conf/99-user_defined_properties.conf
Parsing conf: /root/HiBench/workloads/join/conf/00-join-default.conf
Parsing conf: /root/HiBench/workloads/join/conf/10-join-userdefine.conf
Parsing conf: /root/HiBench/workloads/join/mapreduce/hadoop.conf
start HadoopJoin bench
Export env: HADOOP_EXECUTABLE=/opt/hadoop-2.7.1//bin/hadoop
hdfs rm -r: /opt/hadoop-2.7.1//bin/hadoop --config /opt/hadoop-2.7.1/etc/hadoop fs -rm -r -skipTrash master/HiBench/Join/Output
rm: `master/HiBench/Join/Output': No such file or directory
15/07/24 10:57:44 INFO Configuration.deprecation: mapred.reduce.tasks.speculative.execution is deprecated. Instead, use mapreduce.reduce.speculative
hdfs du -s: /opt/hadoop-2.7.1//bin/hadoop --config /opt/hadoop-2.7.1/etc/hadoop fs -du -s master/HiBench/Join/Output
du: `master/HiBench/Join/Output': No such file or directory
/root/HiBench/bin/functions/workload-functions.sh: line 76: $3: unbound variable
```
where $3 is the size variable in the gen_report function. The spark workloads run successfully in this benchmark. Any ideas on what's the problem?

I run Hadoop-YARN 2.7.1 and Spark 1.4.1 in yarn-client mode.

**Comment by lvsoft** [comment]
The error `du: 'master/HiBench/Join/Output': No such file or directory`  indicates the output directory is not exists, which suggests the workload failed to run successfully.

$3 is the size which parsed from the output of `du ...`. Since `du` failed, that value remains undefined.

Suggest you run `hive -f report/join/mapreduce/rankings_uservisits_join.hive` manually and see what's wrong with it.
