### ISSUE TITLE
HiBench build failed

### ISSUE THREAD

**Issue by Jetsonpaul** [intel-hadoop/HiBench#122]
I setup environment of OpneJDK 1.7.0, Hadoop 2.6.0, python 2.7.6, Spark 1.4.0 in Ubuntu 14.04 64 bit server version.

While building i got following error.

Jetsonpaul@Paultech:~/HiBench/bin# ./build-all.sh
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] hibench
[INFO] nutchindexing
[INFO] mahout
[INFO] hivebench
[INFO] Sparkbench
[INFO] PEGASUS: A Peta-Scale Graph Mining System
[INFO] HiBench data generation tools
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building hibench 4.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
Downloading: https://oss.sonatype.org/content/groups/scala-tools/org/apache/maven/plugins/maven-clean-plugin/2.5/maven-clean-plugin-2.5.pom
Aug 05, 2015 4:58:50 PM org.apache.maven.wagon.providers.http.httpclient.client.protocol.RequestProxyAuthentication process
WARNING: NEGOTIATE authentication error: Invalid name provided (Mechanism level: Cannot locate default realm)
Aug 05, 2015 4:58:50 PM org.apache.maven.wagon.providers.http.httpclient.client.protocol.RequestProxyAuthentication process
WARNING: NTLM authentication error: Credentials cannot be used for NTLM authentication: org.apache.maven.wagon.providers.http.httpclient.auth.UsernamePasswordCredentials
Downloading: http://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-clean-plugin/2.5/maven-clean-plugin-2.5.pom
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] hibench ........................................... FAILURE [3.498s]
[INFO] nutchindexing ..................................... SKIPPED
[INFO] mahout ............................................ SKIPPED
[INFO] hivebench ......................................... SKIPPED
[INFO] Sparkbench ........................................ SKIPPED
[INFO] PEGASUS: A Peta-Scale Graph Mining System ......... SKIPPED
[INFO] HiBench data generation tools ..................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 5.145s
[INFO] Finished at: Wed Aug 05 16:58:51 IST 2015
[INFO] Final Memory: 7M/163M
[INFO] ------------------------------------------------------------------------
[ERROR] Plugin org.apache.maven.plugins:maven-clean-plugin:2.5 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.apache.maven.plugins:maven-clean-plugin:jar:2.5: Could not transfer artifact org.apache.maven.plugins:maven-clean-plugin:pom:2.5 from/to scala-tools.org (https://oss.sonatype.org/content/groups/scala-tools/): Not authorized by proxy , ReasonPhrase:Proxy Authentication Required. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginResolutionException
cp: cannot stat ‘target/*-jar-with-dependencies.jar’: No such file or directory
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] hibench
[INFO] nutchindexing
[INFO] mahout
[INFO] hivebench
[INFO] Sparkbench
[INFO] PEGASUS: A Peta-Scale Graph Mining System
[INFO] HiBench data generation tools
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building hibench 4.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
Downloading: https://oss.sonatype.org/content/groups/scala-tools/org/apache/maven/plugins/maven-clean-plugin/2.5/maven-clean-plugin-2.5.pom
Aug 05, 2015 4:59:04 PM org.apache.maven.wagon.providers.http.httpclient.client.protocol.RequestProxyAuthentication process
WARNING: NEGOTIATE authentication error: Invalid name provided (Mechanism level: Cannot locate default realm)
Aug 05, 2015 4:59:04 PM org.apache.maven.wagon.providers.http.httpclient.client.protocol.RequestProxyAuthentication process
WARNING: NTLM authentication error: Credentials cannot be used for NTLM authentication: org.apache.maven.wagon.providers.http.httpclient.auth.UsernamePasswordCredentials
Downloading: http://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-clean-plugin/2.5/maven-clean-plugin-2.5.pom
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] hibench ........................................... FAILURE [3.182s]
[INFO] nutchindexing ..................................... SKIPPED
[INFO] mahout ............................................ SKIPPED
[INFO] hivebench ......................................... SKIPPED
[INFO] Sparkbench ........................................ SKIPPED
[INFO] PEGASUS: A Peta-Scale Graph Mining System ......... SKIPPED
[INFO] HiBench data generation tools ..................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.668s
[INFO] Finished at: Wed Aug 05 16:59:05 IST 2015
[INFO] Final Memory: 6M/114M
[INFO] ------------------------------------------------------------------------
[ERROR] Plugin org.apache.maven.plugins:maven-clean-plugin:2.5 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.apache.maven.plugins:maven-clean-plugin:jar:2.5: Could not transfer artifact org.apache.maven.plugins:maven-clean-plugin:pom:2.5 from/to scala-tools.org (https://oss.sonatype.org/content/groups/scala-tools/): Not authorized by proxy , ReasonPhrase:Proxy Authentication Required. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginResolutionException
Build failed for spark1.2 and MR1, please check!

**Comment by adrian-wang** [comment]
Looks like this is related to your network environment.

**Comment by Jetsonpaul** [comment]
Whether i need to configure in conf file before i need to build. Because i set hadoop home and spark home in 99-user_defined_properties.conf file.

**Comment by somideshmukh** [comment]
The problem is proxy setting in maven setting.xml file.go to Maven--- Conf --- setting.xml file. there u will see proxy tag.which will commented.un comment that and provide your machine proxy setting and save the file.

**Comment by GayathriMurali** [comment]
This problem looks like a proxy issue. You need to create a file called settings.xml within your ~/.m2 folder. That file will look like this. Please change the host and port value that is specific to your network settings. This should help with your issue

<settings>
<proxies>
<proxy>
<id>optional</id>
<active>true</active>
<protocol>http</protocol>
<username></username>
<password></password>
<host>-->your-proxy-host<--</host>
<port>911</port>
<nonProxyHosts>local.net|some.host.com</nonProxyHosts>
</proxy>
</proxies>
</settings>
