### ISSUE TITLE
How to run HiBench without Spark bench?

### ISSUE THREAD

**Issue by Blueve** [intel-hadoop/HiBench#132]
My experiment is base on Hadoop(0.20.205). I am following `Readme.md` to setup my HiBench.
After I excuted `run-all.sh`, MapReduce Job is successfully completed, but the HiBench continued to submit Spark job and throw error.
```bash
/bin/sh: 1: /PATH/TO/YOUR/SPARK/ROOT/bin/spark-submit: not found
ERROR: Spark job org.apache.spark.examples.JavaWordCount failed to run successfully.
```
Actually, I don't want to run Spark job at all, but i don't know how to run HiBench without Spark bench.

What method can solve that problem? Did I miss some config setting?

Thanks

Blueve

**Comment by GayathriMurali** [comment]
You need to execute individual run scripts in with the workloads for MapReduce. You could also write a script to execute all of this run.sh files. They are located at ../workloads/wordcount/mapreduce/bin/run.sh for example for the wordcount microbenchmark. Please let us know if this makes sense.

**Comment by ilham9649** [comment]
Of course you can do that. You just must edit the configuration file framework.lst in conf directory
