### ISSUE TITLE
Streaming Benchmark Storm Build Failure with master branch

### ISSUE THREAD

**Issue by liyezhang556520** [intel-hadoop/HiBench#147]
error message is 
>[ERROR] Failed to execute goal org.apache.thrift.tools:maven-thrift-plugin:0.1.11:compile (thrift-sources) on project streaming-bench-storm: thrift did not exit cleanly

Thrift output is:
>[ERROR] thrift failed error: /bin/sh: 1: /usr/bin/thrift: not found

**Comment by liyezhang556520** [comment]
@carsonwang , streaming benchmark need thrift to be installed on local machine?

**Comment by carsonwang** [comment]
Yes, it is required when you build it. It need on the path `/usr/bin/thrift`.

**Comment by liyezhang556520** [comment]
need to specify where you installed executable thrift in `src/streambench/stormbench/pom.xml`, the default path in HiBench is `/usr/bin/thrift`, I'm closing this issue.
