### ISSUE TITLE
ERROR: Spark job com.intel.sparkbench.sql.JavaSparkSQLBench failed to run successfully.

### ISSUE THREAD

**Issue by Jetsonpaul** [intel-hadoop/HiBench#151]
root@pts00450-vm8:/home/hduser/HiBench# bin/run-all.sh
Prepare aggregation ...
Exec script: /home/hduser/HiBench/workloads/aggregation/prepare/prepare.sh
Parsing conf: /home/hduser/HiBench/conf/00-default-properties.conf
Parsing conf: /home/hduser/HiBench/conf/10-data-scale-profile.conf
Parsing conf: /home/hduser/HiBench/conf/99-user_defined_properties.conf
Parsing conf: /home/hduser/HiBench/workloads/aggregation/conf/00-aggregation-default.conf
Parsing conf: /home/hduser/HiBench/workloads/aggregation/conf/10-aggregation-userdefine.conf
start HadoopPrepareAggregation bench
hdfs rm -r: /usr/lib/hadoop/bin/hadoop --config /usr/lib/hadoop/etc/hadoop fs -rm -r -skipTrash /usr/local/hadoop/hdfs/HiBench/Aggregation/Input
15/11/24 05:21:31 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Deleted /usr/local/hadoop/hdfs/HiBench/Aggregation/Input
Pages:120000, USERVISITS:1000000
Submit MapReduce Job: /usr/lib/hadoop/bin/hadoop --config /usr/lib/hadoop/etc/hadoop jar /home/hduser/HiBench/src/autogen/target/autogen-4.0-SNAPSHOT-jar-with-dependencies.jar HiBench.DataGen -t hive -b /usr/local/hadoop/hdfs/HiBench/Aggregation -n Input -m 12 -r 6 -p 120000 -v 1000000 -o sequence
15/11/24 05:21:36 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
15/11/24 05:21:39 WARN mapreduce.JobResourceUploader: Hadoop command-line option parsing not performed. Implement the Tool interface and execute your application with ToolRunner to remedy this.
15/11/24 05:23:09 WARN mapreduce.JobResourceUploader: Hadoop command-line option parsing not performed. Implement the Tool interface and execute your application with ToolRunner to remedy this.
15/11/24 05:25:21 INFO HiBench.HiveData: Closing hive data generator...
finish HadoopPrepareAggregation bench
Run aggregation/mapreduce
Exec script: /home/hduser/HiBench/workloads/aggregation/mapreduce/bin/run.sh
Parsing conf: /home/hduser/HiBench/conf/00-default-properties.conf
Parsing conf: /home/hduser/HiBench/conf/10-data-scale-profile.conf
Parsing conf: /home/hduser/HiBench/conf/99-user_defined_properties.conf
Parsing conf: /home/hduser/HiBench/workloads/aggregation/conf/00-aggregation-default.conf
Parsing conf: /home/hduser/HiBench/workloads/aggregation/conf/10-aggregation-userdefine.conf
Parsing conf: /home/hduser/HiBench/workloads/aggregation/mapreduce/hadoop.conf
start HadoopAggregation bench
Export env: HADOOP_EXECUTABLE=/usr/lib/hadoop/bin/hadoop
hdfs rm -r: /usr/lib/hadoop/bin/hadoop --config /usr/lib/hadoop/etc/hadoop fs -rm -r -skipTrash /usr/local/hadoop/hdfs/HiBench/Aggregation/Output
15/11/24 05:25:24 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
rm: `/usr/local/hadoop/hdfs/HiBench/Aggregation/Output': No such file or directory
15/11/24 05:25:27 INFO Configuration.deprecation: mapred.reduce.tasks.speculative.execution is deprecated. Instead, use mapreduce.reduce.speculative
hdfs du -s: /usr/lib/hadoop/bin/hadoop --config /usr/lib/hadoop/etc/hadoop fs -du -s /usr/local/hadoop/hdfs/HiBench/Aggregation/Output
15/11/24 05:28:01 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
finish HadoopAggregation bench
Run aggregation/spark/java
Exec script: /home/hduser/HiBench/workloads/aggregation/spark/java/bin/run.sh
Parsing conf: /home/hduser/HiBench/conf/00-default-properties.conf
Parsing conf: /home/hduser/HiBench/conf/10-data-scale-profile.conf
Parsing conf: /home/hduser/HiBench/conf/99-user_defined_properties.conf
Parsing conf: /home/hduser/HiBench/workloads/aggregation/conf/00-aggregation-default.conf
Parsing conf: /home/hduser/HiBench/workloads/aggregation/conf/10-aggregation-userdefine.conf
Parsing conf: /home/hduser/HiBench/workloads/aggregation/spark/java/java.conf
start JavaSparkAggregation bench
hdfs rm -r: /usr/lib/hadoop/bin/hadoop --config /usr/lib/hadoop/etc/hadoop fs -rm -r -skipTrash /usr/local/hadoop/hdfs/HiBench/Aggregation/Output
15/11/24 05:28:04 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Deleted /usr/local/hadoop/hdfs/HiBench/Aggregation/Output
Export env: SPARKBENCH_PROPERTIES_FILES=/home/hduser/HiBench/report/aggregation/spark/java/conf/sparkbench/sparkbench.conf
Submit Spark job: /home/hduser/spark-1.4.1/bin/spark-submit  --properties-file /home/hduser/HiBench/report/aggregation/spark/java/conf/sparkbench/spark.conf --class com.intel.sparkbench.sql.JavaSparkSQLBench --master local[1]  /home/hduser/HiBench/src/sparkbench/target/sparkbench-4.0-SNAPSHOT-MR2-spark1.4-jar-with-dependencies.jar JavaAggregation /home/hduser/HiBench/report/aggregation/spark/java/conf/../uservisits_aggre.hive
java.lang.ClassNotFoundException: com.intel.sparkbench.sql.JavaSparkSQLBench
15/11/24 05:28:07 INFO util.Utils: Shutdown hook called
ERROR: Spark job com.intel.sparkbench.sql.JavaSparkSQLBench failed to run successfully.
Hint: You can goto /home/hduser/HiBench/report/aggregation/spark/java/conf/../bench.log to check for detailed log.
Opening log tail for you:

java.lang.ClassNotFoundException: com.intel.sparkbench.sql.JavaSparkSQLBench
        at java.lang.Class.forNameImpl(Native Method)
        at java.lang.Class.forName(Class.java:309)
        at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:634)
        at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:170)
        at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:193)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:112)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
15/11/24 05:28:07 INFO util.Utils: Shutdown hook called

ERROR: aggregation/spark/java failed to run successfully.

******************************************************************************************
Mine 99-user_defined_properties.conf details
******************************************************************************************

#Hadoop home
hibench.hadoop.home		/usr/lib/hadoop

#Spark home
hibench.spark.home		/home/hduser/spark-1.4.1

#HDFS master
hibench.hdfs.master		/usr/local/hadoop/hdfs

#Spark master
#standalone mode: `spark://xxx:7077`
#YARN mode: `yarn-client`
#unset: fallback to `local[1]`
hibench.spark.master		local[1]

#======================================================
#Not mandatory but important settings
#======================================================

#`hibench.hadoop.executable` is used to auto probe hadoop version and
#hadoop release, which is critical for further configurations. Most
#cases `hadoop` executable be placed under HADOOP_HOME/bin. However,
#in some cases such as CDH?/MR1, it must be explicitly defined:

hibench.hadoop.executable	/usr/lib/hadoop/bin/hadoop

#`hibench.hadoop.version` will be auto probed according to
#`hibench.hadoop.executable` version information report. However, for
#CDH release, both `hadoop version` of MR1 and MR2 will produce same
#report, which can't probe right MR versions. You'll need to
#explicitly define MR versions here.

hibench.hadoop.version		hadoop2

#`hibench.spark.version` is used to choose which sparkbench workload
#jar. Mostly situation it'll be auto probed. Please override if spark
#version is not probed correctly. 
#Note, supported values: `spark1.2` or `spark1.3`

hibench.spark.version          spark1.4

**Comment by Jetsonpaul** [comment]
Instead of sparkbench-4.0-SNAPSHOT-MR2-spark1.4-jar i can see hibench-4.0-SNAPSHOT.jar inside HiBench/src/sparkbench/target/

**Comment by carsonwang** [comment]
It complained the following jar not exist. Did you run `bin/build-all.sh` before running the workload?
`/home/hduser/HiBench/src/sparkbench/target/sparkbench-4.0-SNAPSHOT-MR2-spark1.4-jar-with-dependencies.jar`

**Comment by Jetsonpaul** [comment]
yes..!!

[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 44.919 s
[INFO] Finished at: 2015-11-23T11:54:09+05:30
[INFO] Final Memory: 56M/121M
[INFO] ------------------------------------------------------------------------
Build all done!

**Comment by carsonwang** [comment]
Can you please confirm the following file exists? This should exit if build is successful. 
` /home/hduser/HiBench/src/sparkbench/target/sparkbench-4.0-SNAPSHOT-MR2-spark1.4-jar-with-dependencies.jar `
I also noticed a problem in your configuration though this may not be related to the error.
`hibench.hdfs.master` should be set to hdfs://hostname:port instead of a path.

**Comment by Jetsonpaul** [comment]
yes this following file exist...
/home/hduser/HiBench/src/sparkbench/target/sparkbench-4.0-SNAPSHOT-MR2-spark1.4-jar-with-dependencies.jar

**Comment by Jetsonpaul** [comment]
I tried lot of times but "ERROR: Spark job com.intel.sparkbench.sql.JavaSparkSQLBench failed to run successfully" not yet solved...!! Please help me to solve this issue..

**Comment by carsonwang** [comment]
Do you still have the issue? This really looks like a build issue. You can have a try with the docker image which helps setup everything on a single node.
https://github.com/intel-hadoop/HiBench/tree/master/docker

**Comment by carsonwang** [comment]
I'd like to confirm if you are using HiBench 4.0 or 5.0? If you are using 4.0, please set `hibench.spark.version` to  `spark1.3` and rebuilt it. This is profile version so you can still run it with Spark 1.4.

**Comment by Jetsonpaul** [comment]
Build all done..!! I tried to run HiBench 4.0 with both Spark 1.5.1 and Spark 1.4.1.. But getting same error java.lang.ClassNotFoundException: com.intel.sparkbench.sql.JavaSparkSQLBench..!!

**Comment by carsonwang** [comment]
This seems to be related to https://github.com/intel-hadoop/HiBench/issues/124. Can you use the master branch which has a better support to Spark 1.4 and 1.5?

**Comment by Jetsonpaul** [comment]
yes, i tried master branch, in that there is no similar issue.

**Comment by carsonwang** [comment]
Thanks for the update. Closing this one now.
