### ISSUE TITLE
Error: Could not find or load main class com.intel.hibench.streambench.StartPeriodic

### ISSUE THREAD

**Issue by DonaldLiujie** [intel-hadoop/HiBench#153]
I am trying to run streamingbench of HiBench-5.0 on 3 nodes' cluster. Every node is a linux container.When I ran script 'gendata.sh', I got the following error:
/*****************************************************************************************************************/
ubuntu@lxc-jie-0:~/hbase/hibench/HiBench/workloads/streamingbench/prepare$ ./gendata.sh
patching args=
Parsing conf: /home/ubuntu/hbase/hibench/HiBench/conf/00-default-properties.conf
Parsing conf: /home/ubuntu/hbase/hibench/HiBench/conf/01-default-streamingbench.conf
Parsing conf: /home/ubuntu/hbase/hibench/HiBench/conf/10-data-scale-profile.conf
Parsing conf: /home/ubuntu/hbase/hibench/HiBench/conf/20-samza-common.conf
Parsing conf: /home/ubuntu/hbase/hibench/HiBench/conf/30-samza-workloads.conf
Parsing conf: /home/ubuntu/hbase/hibench/HiBench/conf/99-user_defined_properties.conf
Parsing conf: /home/ubuntu/hbase/hibench/HiBench/workloads/streamingbench/conf/00-streamingbench.conf
Parsing conf: /home/ubuntu/hbase/hibench/HiBench/workloads/streamingbench/conf/10-streamingbench-userdefine.conf
probe sleep jar: /home/ubuntu/hbase/hadoop/hadoop-2.7.1/share/hadoop/mapreduce/hadoop-mapreduce-client-jobclient-2.7.1-tests.jar
start StreamingBenchPrepare bench
Sending streaming data to kafka, periodically: /usr/lib/jvm/java-7-openjdk-amd64/bin/java -Xmx256M -server -XX:+UseCompressedOops -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled -XX:+CMSScavengeBeforeRemark -XX:+DisableExplicitGC -Djava.awt.headless=true  -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false  -Dcom.sun.management.jmxremote.ssl=false  -Dkafka.logs.dir=bin/../logs -cp /home/ubuntu/hbase/hibench/HiBench/workloads/streamingbench/prepare/../../../src/streambench/datagen/lib/kafka-clients-0.8.1.jar:/home/ubuntu/hbase/hibench/HiBench/src/streambench/datagen/target/datagen-0.0.1-MR2-spark1.2-jar-with-dependencies.jar com.intel.hibench.streambench.StartPeriodic /home/ubuntu/hbase/hibench/HiBench/report/streamingbench/prepare/conf/sparkbench/sparkbench.conf hdfs://10.0.3.90:9000/HiBench/Streaming/Seed/uservisits 0 hdfs://10.0.3.90:9000/HiBench/Streaming/Kmeans/Samples 0
Error: Could not find or load main class com.intel.hibench.streambench.StartPeriodic
/*****************************************************************************************************************/
Cloud you give some suggestions? Do I need set up some environment variables?
Thanks!

**Comment by carsonwang** [comment]
Which Spark version are you using? Instead of build-all, please try to manually build HiBench for your spark version. For example for Spark 1.5 and MR2, run
`mvn clean package -D spark1.5 -D MR2`
