### ISSUE TITLE
There are error information:INFO metastore.MetaStoreDirectSql: MySQL check failed, assuming we are not on mysql: Lexical error at line 1, column 5.  Encountered: "@" (64), after : "". When run HiBench-4.1-branch/workloads/aggregation/spark/java/bin/run.sh

### ISSUE THREAD

**Issue by XianlaiShen** [intel-hadoop/HiBench#154]
Hi,
I have setup Hadoop-2.4.0 Single Node mode,and spark-1.3.0-bin-hadoop2.4, scala-2.11.0,and downloaded the HiBench-4.1-branch,and want to run  the HiBench-4.1-branch/workloads/aggregation/spark/java/bin/run.sh.
it can run sucessfully,and can output  the result,but there are errors information about "INFO metastore.MetaStoreDirectSql: MySQL check failed, assuming we are not on mysql: Lexical error at line 1, column 5.  Encountered: "@" (64), after : "".",as below logs:
Is it normal or not? If it is not right,how can I do the aggregation spark java version test case?
Thanks!

Xianlai Shen

[root@hadoop1 bin]# pwd
/home/shenxianlai/data_shenxianlai/benchmark/HiBench/HiBench_4.1/HiBench-4.1-branch/workloads/aggregation/spark/java/bin
[root@hadoop1 bin]# ls
run.sh
[root@hadoop1 bin]# ./run.sh 
Parsing conf: /home/shenxianlai/data_shenxianlai/benchmark/HiBench/HiBench_4.1/HiBench-4.1-branch/conf/00-default-properties.conf
Parsing conf: /home/shenxianlai/data_shenxianlai/benchmark/HiBench/HiBench_4.1/HiBench-4.1-branch/conf/00-default-properties_org.conf
Parsing conf: /home/shenxianlai/data_shenxianlai/benchmark/HiBench/HiBench_4.1/HiBench-4.1-branch/conf/10-data-scale-profile.conf
Parsing conf: /home/shenxianlai/data_shenxianlai/benchmark/HiBench/HiBench_4.1/HiBench-4.1-branch/conf/99-user_defined_properties.conf
Parsing conf: /home/shenxianlai/data_shenxianlai/benchmark/HiBench/HiBench_4.1/HiBench-4.1-branch/workloads/aggregation/conf/00-aggregation-default.conf
Parsing conf: /home/shenxianlai/data_shenxianlai/benchmark/HiBench/HiBench_4.1/HiBench-4.1-branch/workloads/aggregation/conf/10-aggregation-userdefine.conf
Parsing conf: /home/shenxianlai/data_shenxianlai/benchmark/HiBench/HiBench_4.1/HiBench-4.1-branch/workloads/aggregation/spark/java/java.conf
spark://localhost:7077 localhost
start JavaSparkAggregation bench
hdfs rm -r: /home/shenxianlai/data_shenxianlai/hadoop/hadoop-2.4.0/bin/hadoop --config /home/shenxianlai/data_shenxianlai/hadoop/hadoop-2.4.0/etc/hadoop fs -rm -r -skipTrash hdfs://localhost:9000/HiBench/Aggregation/Output
15/11/27 13:05:48 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Deleted hdfs://localhost:9000/HiBench/Aggregation/Output
Export env: SPARKBENCH_PROPERTIES_FILES=/home/shenxianlai/data_shenxianlai/benchmark/HiBench/HiBench_4.1/HiBench-4.1-branch/report/aggregation/spark/java/conf/sparkbench/sparkbench.conf
Submit Spark job: /home/shenxianlai/data_shenxianlai/spark/spark-1.3.0-bin-hadoop2.4/bin/spark-submit  --properties-file /home/shenxianlai/data_shenxianlai/benchmark/HiBench/HiBench_4.1/HiBench-4.1-branch/report/aggregation/spark/java/conf/sparkbench/spark.conf --class com.intel.sparkbench.sql.JavaSparkSQLBench --master spark://localhost:7077  /home/shenxianlai/data_shenxianlai/benchmark/HiBench/HiBench_4.1/HiBench-4.1-branch/src/sparkbench/target/sparkbench-4.0-SNAPSHOT-MR2-spark1.3-jar-with-dependencies.jar JavaAggregation /home/shenxianlai/data_shenxianlai/benchmark/HiBench/HiBench_4.1/HiBench-4.1-branch/report/aggregation/spark/java/conf/../uservisits_aggre.hive
15/11/27 13:05:53 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
15/11/27 13:06:08 INFO metastore.MetaStoreDirectSql: MySQL check failed, assuming we are not on mysql: Lexical error at line 1, column 5.  Encountered: "@" (64), after : "".
15/11/27 13:06:19 WARN metastore.ObjectStore: Version information not found in metastore. hive.metastore.schema.verification is not enabled so recording the schema version 0.13.1aa
15/11/27 13:06:46 INFO remote.RemoteActorRefProvider$RemotingTerminator: Remoting shut down.
hdfs du -s: /home/shenxianlai/data_shenxianlai/hadoop/hadoop-2.4.0/bin/hadoop --config /home/shenxianlai/data_shenxianlai/hadoop/hadoop-2.4.0/etc/hadoop fs -du -s hdfs://localhost:9000/HiBench/Aggregation/Output
15/11/27 13:06:53 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
finish JavaSparkAggregation bench
[root@hadoop1 bin]# 
[root@hadoop1 bin]#

**Comment by carsonwang** [comment]
Do you have additional configuration for the Hive metastore? By default it uses Derby instead of MySQL. If this is the case, I think you can just ignore this INFO message.

**Comment by XianlaiShen** [comment]
Hi Carson,
I don't have additional configuration for the Hive metastore.Do you mean that if there don't have additional configuration for the Hive metastore,it default uses Derby instead of MySQL,so just ignore this INFO message?
Thanks!

Xianlai Shen

**Comment by carsonwang** [comment]
Yes. It uses a Derby database by default and you can ignore it.

**Comment by XianlaiShen** [comment]
Hi Carson,
Ok, I will close this issue.Thanks a lot to you!

Xianlai Shen
