### ISSUE TITLE
Error: Could not find or load main class com.intel.hibench.streambench.StartPeriodic

### ISSUE THREAD

**Issue by Omacor** [intel-hadoop/HiBench#160]
I am trying to run streambench of HiBench 5.0 in Centos and I want to do some test in Spark1.5 . When running ./workloads/streamingbench/prepare/gendata.sh ,the process raise the following error message:

patching args=
Parsing conf: /usr/local/HiBench-12-05/conf/00-default-properties.conf
Parsing conf: /usr/local/HiBench-12-05/conf/01-default-streamingbench.conf
Parsing conf: /usr/local/HiBench-12-05/conf/10-data-scale-profile.conf
Parsing conf: /usr/local/HiBench-12-05/conf/20-samza-common.conf
Parsing conf: /usr/local/HiBench-12-05/conf/30-samza-workloads.conf
Parsing conf: /usr/local/HiBench-12-05/conf/99-user_defined_properties.conf
Parsing conf: /usr/local/HiBench-12-05/workloads/streamingbench/conf/00-streamingbench.conf
Parsing conf: /usr/local/HiBench-12-05/workloads/streamingbench/conf/10-streamingbench-userdefine.conf
probe sleep jar: /usr/local/hadoop/share/hadoop/mapreduce/hadoop-mapreduce-client-jobclient-2.6.0-tests.jar
spark://master:7077 master
start StreamingBenchPrepare bench
Sending streaming data to kafka, periodically: /usr/local/java/jdk1.7.0_67/bin/java -Xmx256M -server -XX:+UseCompressedOops -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled -XX:+CMSScavengeBeforeRemark -XX:+DisableExplicitGC -Djava.awt.headless=true  -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false  -Dcom.sun.management.jmxremote.ssl=false  -Dkafka.logs.dir=bin/../logs -cp /usr/local/HiBench-12-05/workloads/streamingbench/prepare/../../../src/streambench/datagen/lib/kafka-clients-0.8.1.jar:/usr/local/HiBench-12-05/src/streambench/datagen/target/datagen-0.0.1-MR2-spark1.5-jar-with-dependencies.jar com.intel.hibench.streambench.StartPeriodic /usr/local/HiBench-12-05/report/streamingbench/prepare/conf/sparkbench/sparkbench.conf hdfs://master:9000/HiBench/Streaming/Seed/uservisits 0 hdfs://master:9000/HiBench/Streaming/Kmeans/Samples 0
**Error: Could not find or load main class com.intel.hibench.streambench.StartPeriodic**

finish StreamingBenchPrepare bench

So,I check the file: /usr/local/HiBench-12-05/src/streambench/datagen/target/datagen-0.0.1-MR2-spark1.5-jar-with-dependencies.jar,but only to find there is just a file: datagen-0.0.1-MR2-spark1.3-jar-with-dependencies.jar,not target/datagen-0.0.1-MR2-spark1.5-jar-with-dependencies.jar. 

I build the project by using ./bin/build-all.sh today, so there is something wrong with the build-all.sh,it just package spark1.3, not spark1.4 and spark1.5.

**Comment by carsonwang** [comment]
Yes, this is a known issue and has just been fixed. Can you please try the latest master branch?
Otherwise you can manually build it against Spark 1.5. i.e. `mvn clean package -D spark1.5 -D MR2`

**Comment by qiansl127** [comment]
This issue is resolved by PR https://github.com/intel-hadoop/HiBench/pull/159, close now.
