### ISSUE TITLE
Hadoop 2.7.1 spurious output from 'hadoop' command

### ISSUE THREAD

**Issue by lexpierce** [intel-hadoop/HiBench#164]
With hadoop 2.7.1, using the hadoop command to launch jobs adds the following output:

```
WARNING: Use "yarn jar" to launch YARN applications.
```

Maybe filtering this, or having HiBench execute jar files with "yarn jar" when in an MR2 environment might be a good idea.

**Comment by qiansl127** [comment]
This warning is inessential, work can still get done correctly.
