### ISSUE TITLE
CPU/Memory Usage and SVM algorithm Benchmark

### ISSUE THREAD

**Issue by rendi7936** [intel-hadoop/HiBench#327]
Hello, sir
I using Hibench 5.0 to compare performance between Hadoop and Spark. But, the result only give me the running time, throughput, and throughput/node. I dont find CPU and Memory Usage result in report folder. I am asking this because several journal have this number from Hibench 5.0 like this one http://dx.doi.org/10.1016/j.procs.2016.04.014 .

Am i missing something ?

And second, i want to modify the code to implement SVM algorithm in Hibench. it is ok, isnt it ?
I am asking this because i afraid if i ruin the rules so the benchmark result becomes invalid.

Thanks for your compliments
Rendi

**Comment by carsonwang** [comment]
We recommend using PAT to collect the performance data. 
https://github.com/intel-hadoop/PAT
Yes, you are free to add a new workload.

**Comment by rendi7936** [comment]
So, cpu and memory usage value didnot included in report files after i run Benchmark. Because of that, we can use PAT. Isnt right ?

**Comment by carsonwang** [comment]
There is a monitor.html in the report folder which gives you an overview of the system resource utilization.   You can also use any other tools like PAT to get more detailed data and images.

**Comment by rendi7936** [comment]
Thanks, i forgot to check report folder in detail.
Do hadoop not have built-in Machine Learning Library like MLlib in Spark ?
Can you give an advice what ML library that good for hadoop, especially SVM algorithm ?

**Comment by carsonwang** [comment]
HiBench uses Mahout for ML workloads KMeans and Bayes. You can take a look but it seems SVM has not been supported by Mahout yet.
