### ISSUE TITLE
HiBench 6.0

### ISSUE THREAD

**Issue by carsonwang** [intel-hadoop/HiBench#330]
We are working on HiBench 6.0 and here are the proposed changes in the new version:
- More flexible build:
  HiBench 6.0 supports building only bechmarks for a specific framework. For example, to build the hadoop and spark benchmarks only, we can use the below command:

`mvn -Phadoopbench -Psparkbench clean package`

The workloads are divided into several categories, i.e. micro, sql, graph and ml. We can also build only the workloads in a specific category.

`mvn -Psparkbench -Dmodules -Pmicro clean package`

To specify a spark version, use -Dspark=xxx. By default, it builds against spark 1.6.

`mvn -Dspark=2.0 clean package`
- Spark 2.0 support
  We are going to support both spark 1.6 and 2.0. 
  For Hadoop, we plan to drop the support of Hadoop 1.x. Only hadoop 2.x is supported.
- Streaming benchmark
  A new streaming benchmark will be merged to Hibench 6.0. It supports the following frameworks: Flink, Spark Streaming, Storm, Gearpump. 
- Configurations
  We plan to split the configuraiton to several files and remove some unnecessary configurations.
  The configuration of HiBench will be located at conf/hibench.conf
  Each framework will have its own configuration. i.e. conf/hadoop.conf, conf/spark.conf, etc.
  Each workload will have its own configuration. i.e. conf/workloads/micro/wordcount.conf
- Execution
  The scripts are moved to bin directory. To execute a workload i.e. wordcount, use
  `bin/workloads/micro/wordcount/prepare/prepare.sh`
  `bin/workloads/micro/wordcount/spark/run.sh`

We also plan to remove the following:
The Java and python implementations of the workloads. Only scala version is kept.
Support to Hadoop 1.x

**Comment by carsonwang** [comment]
If you have any questions or requests, welcome to discuss here.

**Comment by rendi7936** [comment]
Is it ok to run Spark 2.0 benchmark with Hibench 5.0 ?
Because, i has run wordcount benchmark using Spark 2.0.0 with Hibench 5.0 in HDP 2.5. Still, it works pretty well. I wonder if there are some other changes in Spark 2.0.0 Benchmark source code.

**Comment by zhangchao0515** [comment]
Hello,I want to know where we can download Hibench6.0 ?
If you can reply. I will thank you so much.

**Comment by carsonwang** [comment]
The 6.0 branch is available at https://github.com/intel-hadoop/HiBench/tree/6.0. It is still working in progress.

**Comment by carsonwang** [comment]
Some workloads in 5.0 may run on Spark 2.0, but others do not. There is a PR #262 to add spark 2.0 support to HiBench 5.0.

**Comment by zhangchao0515** [comment]
thanks very much. I occur some problem when I run wordcount. I wish it can be solved through Hibench 6.0.

> 
![qq 20161021163649](https://cloud.githubusercontent.com/assets/14327647/19592095/ce8019de-97ac-11e6-94a4-0bc4932e35b3.png)

**Comment by zhangchao0515** [comment]
The provided Hibench6.0 also is Hibench5.0???
what difference between of them ?
Whether it can success according "Some workloads in 5.0 may run on Spark 2.0, but others do not. There is a PR #262 to add spark 2.0 support to HiBench 5.0. " ??
we should add or replace according this course???

**Comment by carsonwang** [comment]
As I mentioned earlier, the 6.0 is still WIP. We will add full spark 2.0 support to it soon.

**Comment by zhangchao0515** [comment]
O, I know. I expect for you and this product. I will pay close attention to this.

**Comment by zhangchao0515** [comment]
Thanks for you efforts.

**Comment by zhangchao0515** [comment]
I have some problems.Hope you can give me answer.
![qq 20161022143136](https://cloud.githubusercontent.com/assets/14327647/19617493/ac17faca-9864-11e6-96e9-c6864d94007a.png)
 
![qq 20161022143101](https://cloud.githubusercontent.com/assets/14327647/19617494/b3050bd4-9864-11e6-83c9-ef64b424dced.png)
[99-user_defined_properties.txt](https://github.com/intel-hadoop/HiBench/files/545633/99-user_defined_properties.txt)

**Comment by carsonwang** [comment]
@zhangchao0515 , please create a separated issue for any problem you met in HiBench 5.0.

**Comment by zhangchao0515** [comment]
ok. sorry.

**Comment by zhangchao0515** [comment]
I am very sorry, I have some problem. I need you help.

**Comment by carsonwang** [comment]
@zhangchao0515 , we are not going to support spark 2.0 in HiBench 5. Can you try the 6.0 branch and build it with `mvn clean -Psparkbench -Dspark=2.0 package` to run on Spark 2.0?

**Comment by harschware** [comment]
this issue be closed since 6.0 was merged to master via PR #351
