### ISSUE TITLE
Hibench 5.0 and spark 2.0.1 occur some problem 

### ISSUE THREAD

**Issue by zhangchao0515** [intel-hadoop/HiBench#336]
i know Hibench5.0 doesn't suppose spark2.0. But i according below  
#262 https://github.com/intel-hadoop/HiBench/pull/262

./build-all.sh cann't success. but 
cd src
 mvn clean package -D spark2.0 -D MR2        can success
When i run wordcount occur some problem. Below is my problem.
I have some problems.Hope you can give me answer.
![qq 20161022143136](https://cloud.githubusercontent.com/assets/14327647/19617493/ac17faca-9864-11e6-96e9-c6864d94007a.png)

 I also try set 99-user_defined_properties.conf  
hibench.hadoop.executable   ${hibench.hadoop.home}/bin

![qq 20161022143101](https://cloud.githubusercontent.com/assets/14327647/19617494/b3050bd4-9864-11e6-83c9-ef64b424dced.png)

My hadoop dir is /usr/local/hadoop     version: hadoop-2.7.3
My spark dir is /usr/local/spark        version: spark-2.0.1
I had  have JDK-1.7

this is my conf file
[99-user_defined_properties.txt](https://github.com/intel-hadoop/HiBench/files/545633/99-user_defined_properties.txt)

**Comment by carsonwang** [comment]
`hibench.hadoop.executable` was not set correctly. This is path for the exactuable `hadoop`, i.e. `/usr/local/hadoop/bin/hadoop`.

**Comment by zhangchao0515** [comment]
I had modified it according to you.but it occur some new problem.
![qq 20161027100622](https://cloud.githubusercontent.com/assets/14327647/19752095/42211850-9c2d-11e6-8333-91f78d32b878.png)
this is the file
[wordcount.txt](https://github.com/intel-hadoop/HiBench/files/554819/wordcount.txt)

**Comment by carsonwang** [comment]
Spark 2.0 is supported in  HiBench6.0 now.
