### ISSUE TITLE
Spark 2.0.1 execution failed with HiBench 

### ISSUE THREAD

**Issue by yncxcw** [intel-hadoop/HiBench#343]
hi, all

I have upgraded my Spark from 1.6 to 2.0.1. I found some issues that some of the benchmarks can not successfully finish execution.
 I still use this command to build HiBench and change my spark directory to use version of spark 2.0.1
 mvn clean package -D spark1.6 -D MR2

When I run Wordcount, ths output:
![image](https://cloud.githubusercontent.com/assets/7780675/19874605/15b957d4-9f8c-11e6-9c7d-92f01bd4fcb6.png)
And I also checked the Spark executor log:
![image](https://cloud.githubusercontent.com/assets/7780675/19874646/66d35b4c-9f8c-11e6-9fe6-31136eaaff2d.png)
this error caused the failure of Spark executor. I am wondering if this is caused by the incompatibility of user interface between spark 1.6 and spark2.0.  

BTW, this issue also occurs for Pagerank but, kmeans works fine.

**Comment by carsonwang** [comment]
Spark 2.0 will be fully supported in HiBench 6.0. We are still actively working on this. You can have a try on the 6.0 branch and build it with `mvn clean -Psparkbench -Dspark=2.0 package`. There are some changes in the configuration files and the scripts are moved to the bin directory.

**Comment by yncxcw** [comment]
Thanks, it really helps me.
