### ISSUE TITLE
The configuration "java.bin" doesn't work

### ISSUE THREAD

**Issue by ljp14052** [intel-hadoop/HiBench#346]
Hi
  Two different versions of java have been installed on my machine, and the one I wanted to used is not in _$JAVA_HOME_. Although "java.bin" is configured in 99-user_defined_properties.conf, it is useless.
  Why don't load values from os environment first, then overwrite then from conf files? (in load-config.py line 130~150)

**Comment by carsonwang** [comment]
@ljp14052 , we are looking into this issue.

**Comment by gczsjdy** [comment]
The bug is solved by [PR-367](https://github.com/intel-hadoop/HiBench/pull/367). @ljp14052
