### ISSUE TITLE
hibench 5.0 not support well to spark2.0

### ISSUE THREAD

**Issue by Minkyolyy** [intel-hadoop/HiBench#350]
dou you have a benchmark to support spark2.0?

**Comment by carsonwang** [comment]
Spark 2.0 is fully supported in HiBench 6.0. We are still actively working on other features in 6.0. You can have a try on the 6.0 branch and build it with  `mvn clean -Psparkbench -Dspark=2.0` package . There are some changes in the configuration files and the scripts are moved to the bin directory.

**Comment by Minkyolyy** [comment]
when i execute ./bin/build_all.sh,follow error was happend

[root@demo109 bin]# ./build-all.sh 
./build-all.sh: line 22: cd: /home/Minkyo/HiBench-6.0/src: No such file or directory
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.109 s
[INFO] Finished at: 2016-11-08T10:43:51+08:00
[INFO] Final Memory: 6M/303M
[INFO] ------------------------------------------------------------------------
[ERROR] The goal you specified requires a project to execute but there is no POM in this directory (/home/Minkyo/HiBench-6.0/bin). Please verify you invoked Maven from the correct directory. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MissingProjectException
cp: cannot stat `target/*-jar-with-dependencies.jar': No such file or directory
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.109 s
[INFO] Finished at: 2016-11-08T10:43:52+08:00
[INFO] Final Memory: 5M/239M

**Comment by Minkyolyy** [comment]
there is no src dir  why?

**Comment by Minkyolyy** [comment]
When released HiBench6.0?

**Comment by carsonwang** [comment]
You can build at the root directory using `mvn clean -Psparkbench -Dspark=2.0 package`. See more details #330 . 
We'll update the docs soon.

**Comment by jnj2001** [comment]
Hi,

Just tried the 6.0 branch. Building most of the benchmarks works, except for:
mvn -Dspark=2.0 -Psparkbench clean package
[INFO] sparkbench-sql ..................................... SUCCESS [  3.979 s]
[INFO] sparkbench-streaming ............................... FAILURE [  1.205 s]
[INFO] sparkbench project assembly ........................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 59.342 s
[INFO] Finished at: 2016-11-08T22:44:31-08:00
[INFO] Final Memory: 74M/3055M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project sparkbench-streaming: Could not resolve dependencies for project com.intel.hibench.sparkbench:sparkbench-streaming:jar:6.0-SNAPSHOT: Failed to collect dependencies at org.apache.spark:spark-streaming-kafka_2.11:jar:2.0.0: Failed to read artifact descriptor for org.apache.spark:spark-streaming-kafka_2.11:jar:2.0.0: Could not transfer artifact org.apache.spark:spark-streaming-kafka_2.11:pom:2.0.0 from/to scala-tools.org (https://oss.sonatype.org/content/groups/scala-tools/): Access denied to: https://oss.sonatype.org/content/groups/scala-tools/org/apache/spark/spark-streaming-kafka_2.11/2.0.0/spark-streaming-kafka_2.11-2.0.0.pom , ReasonPhrase:Forbidden. -> [Help 1]

Any suggestions?
Thanks

**Comment by carsonwang** [comment]
@jnj2001, thanks for trying HiBench 6.0. The issue you mentioned is fixed in the master branch. We have merged 6.0 branch to master so the 6.0 branch will not be updated any more. Please try the master branch. Thanks!

**Comment by jnj2001** [comment]
thanks for the quick response.

master works. 
Thanks
