### ISSUE TITLE
Building Streaming Benchmark Zookeeper Helper Utils 0.1-SNAPSHOT

### ISSUE THREAD

**Issue by jiaqianjing** [intel-hadoop/HiBench#359]
build-info:
`[INFO] Building Streaming Benchmark Zookeeper Helper Utils 0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
Downloading: https://repository.apache.org/content/groups/public/org/apache/kafka/kafka_2.10/0.8.2.1/kafka_2.10-0.8.2.1.pom
Nov 09, 2016 3:34:16 PM org.apache.maven.wagon.providers.http.httpclient.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.SocketException) caught when processing request to {s}->https://repository.apache.org:443: Connection reset
Nov 09, 2016 3:34:16 PM org.apache.maven.wagon.providers.http.httpclient.impl.execchain.RetryExec execute
INFO: Retrying request to {s}->https://repository.apache.org:443
Nov 09, 2016 3:35:00 PM org.apache.maven.wagon.providers.http.httpclient.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.SocketException) caught when processing request to {s}->https://repository.apache.org:443: Connection reset
Nov 09, 2016 3:35:00 PM org.apache.maven.wagon.providers.http.httpclient.impl.execchain.RetryExec execute
INFO: Retrying request to {s}->https://repository.apache.org:443`

what should I do？

**Comment by carsonwang** [comment]
Look like you are building the old 5.0 version. The master branch (6.0) has a much better streaming benchmark. Please give it a shot!

**Comment by jiaqianjing** [comment]
@carsonwang hah ! ? Where is HiBench 6.0 ?  I didn't see the 6.0 release in the repository of intel-hadoop

**Comment by jiaqianjing** [comment]
@carsonwang  I see. Thanks guys

**Comment by jiaqianjing** [comment]
Hi，@carsonwang  When I upgraded the version, I have another problem. I used HDP 2.4,so my `hadoop-mapreduce-examples.jar` in `/usr/hdp/2.4.0.0-169/hadoop-mapreduce` not `/usr/hdp/2.4.0.0-169/hadoop`.
How do I set up my configuration file?
when I run wordcount/prepare/.prepare.sh, I got the following feedback：
`Parsing conf: /home/hdfs/HiBench-6.0/conf/workloads/micro/wordcount.conf
Traceback (most recent call last):
  File "/home/hdfs/HiBench-6.0/bin/functions/load_config.py", line 723, in <module>
    load_config(conf_root, workload_configFile, workload_folder, patching_config)
  File "/home/hdfs/HiBench-6.0/bin/functions/load_config.py", line 208, in load_config
    generate_optional_value()
  File "/home/hdfs/HiBench-6.0/bin/functions/load_config.py", line 641, in generate_optional_value
    probe_hadoop_examples_jars()
  File "/home/hdfs/HiBench-6.0/bin/functions/load_config.py", line 400, in probe_hadoop_examples_jars
    examples_jars_candidate_list, "hibench.hadoop.examples.jar")
  File "/home/hdfs/HiBench-6.0/bin/functions/load_config.py", line 128, in exactly_one_file
    " matches no files, please set `" + config_name + "` manually"
AssertionError: The pattern /usr/hdp/2.4.0.0-169/hadoop/hadoop-mapreduce-examples.jar matches no files, please set `hibench.hadoop.examples.jar` manually
/home/hdfs/HiBench-6.0/bin/functions/workload-functions.sh: line 38: .: filename argument required
.: usage: . filename [arguments]
start HadoopPrepareWordcount bench
./prepare.sh: line 26: INPUT_HDFS: unbound variable`

**Comment by carsonwang** [comment]
@jiaqianjing, since #361  is open for the new issue. I'll close this one.
