### ISSUE TITLE
Execution Error in HiBench 6.0

### ISSUE THREAD

**Issue by EddiePi** [intel-hadoop/HiBench#362]
I am trying some spark benchmark using HiBench 6.0. But some error occured.
here is an error when I was trying to execute prepare.sh for bayes:
`$ bin/workloads/ml/bayes/prepare/prepare.sh 
patching args=
Parsing conf: /home/eddie/HiBench-6.0/conf/hadoop.conf
Parsing conf: /home/eddie/HiBench-6.0/conf/hibench.conf
Parsing conf: /home/eddie/HiBench-6.0/conf/spark.conf
Parsing conf: /home/eddie/HiBench-6.0/conf/workloads/ml/bayes.conf
Traceback (most recent call last):
  File "/home/eddie/HiBench-6.0/bin/functions/load_config.py", line 723, in <module>
    load_config(conf_root, workload_configFile, workload_folder, patching_config)
  File "/home/eddie/HiBench-6.0/bin/functions/load_config.py", line 208, in load_config
    generate_optional_value()
  File "/home/eddie/HiBench-6.0/bin/functions/load_config.py", line 641, in generate_optional_value
    probe_hadoop_examples_jars()
  File "/home/eddie/HiBench-6.0/bin/functions/load_config.py", line 400, in probe_hadoop_examples_jars
    examples_jars_candidate_list, "hibench.hadoop.examples.jar")
  File "/home/eddie/HiBench-6.0/bin/functions/load_config.py", line 128, in exactly_one_file
    " matches no files, please set `" + config_name + "` manually"
AssertionError: The pattern ${HADOOP_HOME}/hadoop-mapreduce-examples.jar matches no files, please set `hibench.hadoop.examples.jar` manually
/home/eddie/HiBench-6.0/bin/functions/workload-functions.sh: line 38: .: filename argument required
.: usage: . filename [arguments]
start HadoopPrepareBayes bench
bin/workloads/ml/bayes/prepare/prepare.sh: line 26: INPUT_HDFS: unbound variable`

So how to solve this problem?

**Comment by harschware** [comment]
I just commented in #361 that putting the 00 users conf file from 5.0 branch into conf directory, might solve the problem.  I seem to run into other problems next, but my cluster may be having a problem.

**Comment by EddiePi** [comment]
@harschware Thanks! I have solved the problem.
In the `spark.conf` and `hadoop.conf` file, the path to Hadoop home and Spark home should be written as the absolute path to the directories.
I used to write it as the environment variables, say $HADOOP_HOME, and then obtained error.

**Comment by carsonwang** [comment]
Thanks @EddiePi and @harschware . We'll take a look at this to see if we can support setting the path as an environment variable. @gczsjdy

**Comment by gczsjdy** [comment]
I have solved this by [PR-365](https://github.com/intel-hadoop/HiBench/pull/365), you can set environment variables in conf files freely after that one is merged. @EddiePi @harschware
