### ISSUE TITLE
Heat maps do not work 

### ISSUE THREAD

**Issue by prajay** [intel-hadoop/HiBench#368]
Currently in any monitor.html heatmaps are not generated due to the following error:

Uncaught TypeError: Cannot read property '' of undefined(…)(anonymous function) @ monitor.html:302a.each @ highcharts.js:26(anonymous function) @ monitor.html:295a.(anonymous function) @ highcharts.js:18render @ highcharts.js:297(anonymous function) @ highcharts.js:256a.each @ highcharts.js:26renderSeries @ highcharts.js:255render @ highcharts.js:257firstRender @ highcharts.js:260init @ highcharts.js:237(anonymous function) @ data.js:24a.(anonymous function) @ highcharts.js:18getArgs @ highcharts.js:236a.Chart @ highcharts.js:235gen_heatmap_options @ monitor.html:241(anonymous function) @ monitor.html:324o @ jquery-1.7.2.min.js:2fireWith @ jquery-1.7.2.min.js:2ready @ jquery-1.7.2.min.js:2B @ jquery-1.7.2.min.js:2

This can be fixed by making the change mentioned in the attached file to bin/functions/chart-template.html
[diff.txt](https://github.com/intel-hadoop/HiBench/files/583512/diff.txt)

**Comment by carsonwang** [comment]
Thanks @prajay ! Can you please open a pull request for this issue?
