### ISSUE TITLE
spark java/scala/python run sql : ERROR KeyProviderCache: Could not find uri with key [dfs.encryption.key.provider.uri] to create a keyProvider !!

### ISSUE THREAD

**Issue by jiaqianjing** [intel-hadoop/HiBench#370]
when i was runnning sql(join,scan,etc) ,i always have an error:
` ERROR KeyProviderCache: Could not find uri with key [dfs.encryption.key.provider.uri] to create a keyProvider !!
`
thx a lot

**Comment by carsonwang** [comment]
Close as duplicate #376
