### ISSUE TITLE
spark on aggregation and scan has one problem about KeyProviderCache

### ISSUE THREAD

**Issue by jiaqianjing** [intel-hadoop/HiBench#376]
16/11/13 22:33:26 ERROR KeyProviderCache: Could not find uri with key [dfs.encryption.key.provider.uri] to create a keyProvider !!

**Comment by carsonwang** [comment]
Did the workload actually succeed? If HDFS encryption is disabled and the workload succeed, I think this can be ignored.

**Comment by carsonwang** [comment]
We now bypass this kind of errors that can be ignored.  #387
