### ISSUE TITLE
metrics_reader.sh: line 28: unbound variable

### ISSUE THREAD

**Issue by Gnillor** [intel-hadoop/HiBench#392]
In HiBench/bin/workloads/streaming/identity/common/metrics_reader.sh, the ${TREAMING_KAFKA_HOME} of line 28 should be
${KAFKA_HOME}, otherwise it fails with the error: unbound variable

**Comment by carsonwang** [comment]
This looks like a typo. It should be `STREAMING_KAFKA_HOME` @ConeyLiu

**Comment by ConeyLiu** [comment]
I'm sorry for that. Fixed in #393.
