### ISSUE TITLE
Benchmarking for nutchindexing

### ISSUE THREAD

**Issue by prashanthig** [intel-hadoop/HiBench#4]
HI, I am trying to run the Nutchindexing job (https://github.com/hibench/HiBench-2.1/tree/f1d43780f5ae813ccd4e891e353429e7871c9c41). It says that "Total input paths to process is 0".
Can anyone help me in understanding what the programs expecting as input and where should i give it?

Thanks,
Prashanthi

**Comment by adrian-wang** [comment]
Closed as resolved
