### ISSUE TITLE
Createtable failing with sentry protected cluster.

### ISSUE THREAD

**Issue by vijaynirm** [intel-hadoop/HiBench#408]
My cluster is Sentry Enabled. though we set all sentry enable rules, still create table command is failing.

/opt/cloudera/parcels/CDH/lib/spark/bin/spark-submit   --class com.intel.hibench.sparkbench.sql.ScalaSparkSQLBench --master yarn-client --num-executors 2 --executor-cores 4 --executor-memory 4g /xxxe/XXXX/xxxxxxxxxxxxx/sparkbench/assembly/target/sparkbench-assembly-6.1-SNAPSHOT-dist.jar ScalaJoin /xxxe/XXXX/xxxxxxxxxxxxx/report/join/spark/conf/../rankings_uservisits_join.hive

CREATE EXTERNAL TABLE rankings (pageURL STRING, pageRank INT, avgDuration INT) ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde' STORED AS  SEQUENCEFILE LOCATION '/xxxxxxxxxxxx/rankings'

17/01/10 08:51:07 INFO ql.Driver: Starting task [Stage-0:DDL] in serial mode
17/01/10 08:51:08 ERROR exec.DDLTask: org.apache.hadoop.hive.ql.metadata.HiveException: MetaException(message:User XXXXX does not have privileges for CREATETABLE)
        at org.apache.hadoop.hive.ql.metadata.Hive.createTable(Hive.java:764)
        at org.apache.hadoop.hive.ql.exec.DDLTask.createTable(DDLTask.java:4082)

between, able to execute the query in Hue successfully.

Any idea?

**Comment by vijaynirm** [comment]
This one was fixed. I need to give the fullpath including the nameservice in workload.function for hive external location.

**Comment by jmbertoncelli** [comment]
Hello!  I do have the same issue but I do not understand what you did in order to make it to work.
Would you be able to provide an example of what was the fix in order to make this create external table to work?

Thanks in advance.

JM
