### ISSUE TITLE
Regarding an issue with preparing DFSIOE workload

### ISSUE THREAD

**Issue by Saif-KF** [intel-hadoop/HiBench#441]
Dears,

I need your kind help on an issue relevant to preparing DFSIOE workload on Hadoop HDP:
When I run "bin/workloads/micro/dfsioe/prepare/prepare.sh" , I get an error "Not a valid JAR: /root/HiBench/autogen/target/autogen-6.1-SNAPSHOT-jar-with-dependencies.jar"?

For other workloads such as "wordcount" & "sort", they get prepared perfectly by running:
"bin/workloads/micro/wordcount/prepare/prepare.sh" &
"bin/workloads/micro/sort/prepare/prepare.sh"

![dfsioe-error](https://cloud.githubusercontent.com/assets/434252/24823384/875226a4-1c06-11e7-946d-84a14106842a.png)

[bench-dfsioe.txt](https://github.com/intel-hadoop/HiBench/files/891428/bench-dfsioe.txt)

**Comment by Saif-KF** [comment]
Any help dears. I am stuck there

**Comment by Saif-KF** [comment]
Dears,

Your kind support? this issue is a bottleneck in my project?
How to generate needed JAR file inside "autogen" folder, I tried to run "mvn install" from inside the "autogen", but I got the below error:
![mvn-install-error](https://cloud.githubusercontent.com/assets/434252/24838869/36387846-1d59-11e7-8d5e-600a1a6b5bb1.png)

**Comment by carsonwang** [comment]
Please follow the document below to build HiBench. The JAR of autogen will be created if the build succeeds. https://github.com/intel-hadoop/HiBench/blob/master/docs/build-hibench.md

**Comment by Saif-KF** [comment]
Thank you very much @carsonwang . I was about to update you about this issue.
before I have build HiBench using: "mvn -Phadoopbench -Dmodules -Pmicro -Dscala=2.11 clean package ".
Yesterday I have run "mvn install" inside the HiBench folder and all modules and frameworks have installed and now  I can see Jar file inside "autogen" folder.

Is what I did ok? I mean " mvn install"?

**Comment by carsonwang** [comment]
Yes. That also works. The command you used earlier should also work. I just tried and and was able to the see the Jar inside "autogen" folder.

**Comment by Saif-KF** [comment]
Thank you very much @carsonwang  for your clarification.
