### ISSUE TITLE
Mention support for Spark 2.1 under ' Supported Hadoop/Spark/Flink/Storm/Gearpump releases:'

### ISSUE THREAD

**Issue by Puttole** [intel-hadoop/HiBench#477]
In the https://github.com/intel-hadoop/HiBench link, the supported list of releases is mentioned as below.

Supported Hadoop/Spark/Flink/Storm/Gearpump releases:

Hadoop: Apache Hadoop 2.x, CDH5, HDP
Spark: Spark 1.6.x, Spark 2.0.x
Flink: 1.0.3
Storm: 1.0.1
Gearpump: 0.8.1
Kafka: 0.8.2.2

It does not claim support for Spark 2.1. As per, https://github.com/intel-hadoop/HiBench/blob/master/docs/build-hibench.md, it is clear that HiBench supports Spark 2.1.

**Comment by gczsjdy** [comment]
You are right, I will create a PR to resolve this. @Puttole Thanks.

**Comment by carsonwang** [comment]
Thanks @Puttole and @gczsjdy. The doc was updated.
