### ISSUE TITLE
DFSIOE

### ISSUE THREAD

**Issue by faizabidi** [intel-hadoop/HiBench#494]
Hi. Can somebody please tell me what does the below error mean? I wanted to run DFSIO test for "huge" workload and encountered this. 

"INFO dfsioe.TestDFSIOEnh: Please adjust your test workload and try again."

**Comment by sophia-sun** [comment]
could you please attach your full log? @faizabidi

**Comment by BearL222** [comment]
Is the problem solved? I met the same problem. Thanks.

**Comment by faizabidi** [comment]
@BearL222 I decided to use the DFSIO provided by Hadoop jar files instead. 

# DFSIO WRITE
hadoop jar /usr/hdp/2.6.2.0-205/hadoop-mapreduce/hadoop-mapreduce-client-jobclient-tests.jar TestDFSIO -write -nrFiles 128 -fileSize 8192

# DFSIO READ
hadoop jar /usr/hdp/2.6.2.0-205/hadoop-mapreduce/hadoop-mapreduce-client-jobclient-tests.jar TestDFSIO -read -nrFiles 128 -fileSize 8192

Try to play with nrFiles and fileSize parameters and see what works best for your cluster. The idea is to reduce the standard error as much as possible.
