### ISSUE TITLE
Authenticity of hosts can't be established and permission denied.

### ISSUE THREAD

**Issue by xiaofmao** [intel-hadoop/HiBench#537]
I'm trying to run HiBench against a 4-node HDP (HortonWorks Data Platform) cluster. HiBench was built successfully and then I tried execute some micro workloads, like wordcount, dfsio, terasort. At the 1st time, quite a lot of permission denied errors were reported because my local linux account doesn't have the access to hdfs work folders (whose owner is user 'hdfs'), so I change the owner of HiBench to user 'hdfs' accordingly. Finally the HiBench job can be executed but there're still two kinds of warning during the execution.
**1) Authenticity of hosts can't be established**
**2) Permission denied in workload_functions.sh: line 115: /dev/stderr**
Can any one help to advise how to the configuration should be made to fix the errors?

====== detailed execution results as below (errors are highlighted) ======
azurestack@hdp-master:~$ sudo -u hdfs ./HiBench/bin/workloads/micro/wordcount/prepare/prepare.sh
patching args=
Parsing conf: /home/azurestack/HiBench/conf/hadoop.conf
Parsing conf: /home/azurestack/HiBench/conf/hibench.conf
Parsing conf: /home/azurestack/HiBench/conf/workloads/micro/wordcount.conf
probe sleep jar: /usr/hdp/current/hadoop-client/../hadoop-mapreduce/hadoop-mapreduce-client-jobclient-tests.jar
start HadoopPrepareWordcount bench
**/home/azurestack/HiBench/bin/functions/workload_functions.sh: line 115: /dev/stderr: Permission denied**
rm: `hdfs://hdp-master.97cccb0d-d2c1-4aaa-98af-103b6ff41607.internal.shanghai.local:8020/HiBench/Wordcount/Input': No such file or directory
Submit MapReduce Job: /usr/hdp/current/hadoop-client/bin/hadoop --config /usr/hdp/current/hadoop-client/etc/hadoop jar /usr/hdp/current/hadoop-client/../hadoop-mapreduce/hadoop-mapreduce-examples.jar randomtextwriter -D mapreduce.randomtextwriter.totalbytes=32000 -D mapreduce.randomtextwriter.bytespermap=4000 -D mapreduce.job.maps=8 -D mapreduce.job.reduces=8 hdfs://hdp-master.97cccb0d-d2c1-4aaa-98af-103b6ff41607.internal.shanghai.local:8020/HiBench/Wordcount/Input
**The authenticity of host 'hdp-worker02.97cccb0d-d2c1-4aaa-98af-103b6ff41607.internal.shanghai.local (10.0.0.6)' can't be established.
ECDSA key fingerprint is 98:5f:38:61:6f:d7:2a:ff:45:47:14:29:a0:bd:d5:78.
Are you sure you want to continue connecting (yes/no)? The authenticity of host 'hdp-worker03.97cccb0d-d2c1-4aaa-98af-103b6ff41607.internal.shanghai.local (10.0.0.7)' can't be established.
ECDSA key fingerprint is bd:cc:fd:81:e7:48:7e:69:5c:d1:4e:d8:97:c6:64:8d.
Are you sure you want to continue connecting (yes/no)? The authenticity of host 'hdp-worker04.97cccb0d-d2c1-4aaa-98af-103b6ff41607.internal.shanghai.local (10.0.0.8)' can't be established.
ECDSA key fingerprint is a3:55:a4:f2:3c:ce:95:a3:6b:08:4b:65:9c:c6:69:7a.
Are you sure you want to continue connecting (yes/no)? The authenticity of host 'hdp-master.97cccb0d-d2c1-4aaa-98af-103b6ff41607.internal.shanghai.local (10.0.0.4)' can't be established.
ECDSA key fingerprint is 36:ac:7b:e5:1a:80:1a:03:5d:bb:bf:e9:8a:3e:57:d2.**
Are you sure you want to continue connecting (yes/no)? 18/01/22 02:31:29 INFO client.RMProxy: Connecting to ResourceManager at hdp-worker02.97cccb0d-d2c1-4aaaThe job took 14 seconds.
finish HadoopPrepareWordcount bench

**Comment by carsonwang** [comment]
You may want to run HiBench on the node that can ssh to other nodes without password (i.e. the master node). For the permission issue, you can set the proper permission on HiBench's root HDFS direcotory hdfs://[your master]/HiBench

**Comment by Aamer012** [comment]
Can u please tell what parameters have to set correctly, for ssh to run without pwd when cluster is already ssh pwd-less configured?

**Comment by xiaofmao** [comment]
I've set password-less using my local user "hdpuser" during HDP cluster deployment. But I notice there is a new account "hdfs" created during HDP deployment and I have no idea about the password for "hdfs".
For HiBench, firstly I tried to install and run with "hdpuser", but it showed that "hdpuser" doesn't have access to the files in HDFS. Then I tried to run HiBench with ROOT access, but still I got the access error.
So finally I changed the owner of HiBench to "hdfs", and execute HiBench jobs with "sudo -u hdfs XXX" like the detailed execution record I posted. The job can be executed but with warnings.
@carsonwang do you have any suggestion which user I shall set as owner of HiBench (local user, hdfs, or root)?

**Comment by carsonwang** [comment]
You can just use the normal user "hdpuser". Usually you should have already created the user directory on HDFS like  hdfs://[IP]:8020/user/hdpuser and have the full  access. Then you can configure the Hibench HDFS directory `hibench.hdfs.master` to this path in `conf/hadoop.conf`. All HiBench data will be written to your user's directory on HDFS.

**Comment by xiaofmao** [comment]
@carsonwang Really appreciate! This solution is helpful to solve the 2nd issue that I met. But for the 1st one, authenticity of hosts still can't be established. It's a little strange because I've already configured password-less sign-in for my local account. And I could also do SSH to all nodes properly without password input.
But during the execution of HiBench job, I received warnings as below. Is there any additional "password-less" which needs to be configured?

====== detailed execution results as below (errors are highlighted) ======
azurestack@hdp-master:~/HiBench$ ./bin/workloads/micro/wordcount/prepare/prepare.sh
patching args=
Parsing conf: /home/azurestack/HiBench/conf/hadoop.conf
Parsing conf: /home/azurestack/HiBench/conf/hibench.conf
Parsing conf: /home/azurestack/HiBench/conf/workloads/micro/wordcount.conf
probe sleep jar: /usr/hdp/current/hadoop-client/../hadoop-mapreduce/hadoop-mapreduce-client-jobclient-tests.jar
start HadoopPrepareWordcount bench
hdfs rm -r: /usr/hdp/current/hadoop-client/bin/hadoop --config /usr/hdp/current/hadoop-client/etc/hadoop fs -rm -r -skipTrash hdfs://hdp-master.97cccb0d-d2c1-4aaa-98af-103b6ff41607.internal.shanghai.local:8020/user/azurestack/HiBench/Wordcount/Input
Deleted hdfs://hdp-master.97cccb0d-d2c1-4aaa-98af-103b6ff41607.internal.shanghai.local:8020/user/azurestack/HiBench/Wordcount/Input
Submit MapReduce Job: /usr/hdp/current/hadoop-client/bin/hadoop --config /usr/hdp/current/hadoop-client/etc/hadoop jar /usr/hdp/current/hadoop-client/../hadoop-mapreduce/hadoop-mapreduce-examples.jar randomtextwriter -D mapreduce.randomtextwriter.totalbytes=32000 -D mapreduce.randomtextwriter.bytespermap=4000 -D mapreduce.job.maps=8 -D mapreduce.job.reduces=8 hdfs://hdp-master.97cccb0d-d2c1-4aaa-98af-103b6ff41607.internal.shanghai.local:8020/user/azurestack/HiBench/Wordcount/Input
**The authenticity of host 'hdp-worker02.97cccb0d-d2c1-4aaa-98af-103b6ff41607.internal.shanghai.local (10.0.0.6)' can't be established.
ECDSA key fingerprint is 98:5f:38:61:6f:d7:2a:ff:45:47:14:29:a0:bd:d5:78.
Are you sure you want to continue connecting (yes/no)? The authenticity of host 'hdp-worker03.97cccb0d-d2c1-4aaa-98af-103b6ff41607.internal.shanghai.local (10.0.0.7)' can't be established.
ECDSA key fingerprint is bd:cc:fd:81:e7:48:7e:69:5c:d1:4e:d8:97:c6:64:8d.
Are you sure you want to continue connecting (yes/no)? The authenticity of host 'hdp-master.97cccb0d-d2c1-4aaa-98af-103b6ff41607.internal.shanghai.local (10.0.0.4)' can't be established.
ECDSA key fingerprint is 36:ac:7b:e5:1a:80:1a:03:5d:bb:bf:e9:8a:3e:57:d2.
Are you sure you want to continue connecting (yes/no)? The authenticity of host 'hdp-worker04.97cccb0d-d2c1-4aaa-98af-103b6ff41607.internal.shanghai.local (10.0.0.8)' can't be established.
ECDSA key fingerprint is a3:55:a4:f2:3c:ce:95:a3:6b:08:4b:65:9c:c6:69:7a.**
Are you sure you want to continue connecting (yes/no)? 18/02/02 05:23:37 INFO client.RMProxy: Connecting to ResourceManager at hdp-worker02.97cccb0d-d2c1-4aaaThe job took 13 seconds.
finish HadoopPrepareWordcount bench

**Comment by carsonwang** [comment]
Do you see the same message if you manually ssh to the worker like ssh hdp-worker02.97cccb0d-d2c1-4aaa-98af-103b6ff41607.internal.shanghai.local ? I am not sure if it is because something changed after you setup password-less ssh or you used a different user when setup? You may want to resolve it first and make sure you can manually ssh to the host name without issues.

**Comment by xiaofmao** [comment]
@carsonwang SSH to the FQDN seems to be the issue here. Although I can "ssh hdp-worker02" successfully, but when I tried "ssh hdp-worker02.97cccb0d-d2c1-4aaa-98af-103b6ff41607.internal.shanghai.local" for the 1st time, the confirmation was shown. So after manually ssh to all of nodes, and then re-executed the HiBench job, there is no longer error message there.
Thanks so much for kind suggestion!

**Comment by carsonwang** [comment]
Good to know it works now and you are welcome, @xiaofmao .
I'll close this. Please open new issues if you have any other questions.
