### ISSUE TITLE
How to add Spark submit conf

### ISSUE THREAD

**Issue by xiandong79** [intel-hadoop/HiBench#552]
I want to add

```
--queue A
--conf spark.yarn.executor.nodeLabelExpression=Y
```

in spark-submit.  Can I add the above lines in spark.conf directly?

**Comment by xiandong79** [comment]
@cemsbr @carsonwang

**Comment by gczsjdy** [comment]
the latter can work, while the former can't
for the former, you can manually add it in run_spark_job

**Comment by petro-rudenko** [comment]
If you're on yarn `--queue` is the same as `spark.yarn.queue A`
