### ISSUE TITLE
AssertionError: Get workers from spark master's web UI page failed

### ISSUE THREAD

**Issue by aaudiber** [intel-hadoop/HiBench#556]
Hibench uses the below snippet to probe the Spark web UI for worker hostnames. Note that the default `worker_port` is `8081`.

https://github.com/intel-hadoop/HiBench/blob/b90e5ce3f9aee8fe812b7fdfd4015637479eedfd/bin/functions/load_config.py#L563-L570

Snippet from curling the Spark web UI:
```
        <a href="http://worker-9:8081">
              worker-20180810192952-worker-9-34189
```

This consistently started throwing `list index out of range`, and will continue to for the next 10 days. This is because the current year ends in **8**, the current month is **08**, and the current day starts with **1**

**Comment by gczsjdy** [comment]
lol interesting corner case, thanks @aaudiber
