### ISSUE TITLE
how to rebuild nutch-1.2.jar??

### ISSUE THREAD

**Issue by NTNguyen** [intel-hadoop/HiBench#6]
Hi ,
I want to modify  IndexingMapReduce.java file from nutch-indexing, but I'm not ale to recompile it back to the nutch-1.2.jar file. When the ran the provided build.xml file, it complained that it cant find the package org.apache.hadoop.* . But I already configure my HADOOP_HOME in hibench-config.sh. Is any thing else I need to provide in my build?
Any help would be appriciated. 

Nhung

**Comment by qiansl127** [comment]
For HiBench 3.0 release, nutch bin is downloaded by maven. If you want to recompile nutch, you need to check the dependent jars in nutch folder, and it has no relation to HiBench settings.
