### ISSUE TITLE
hivebench

### ISSUE THREAD

**Issue by KofDossou** [intel-hadoop/HiBench#73]
How do I  run hivebench to view results according to SIGMOD paaper? I also did run hive --service metastore to establish concurrency as stated.The command /HiBench/hivebench/conf$ configure.sh
configure.sh: command not found
Am benchmarking hivebench for a my Master projects. Please any input as to what am doing wrong is appreciated.

**Comment by KofDossou** [comment]
I located to hivebench/bin folder and I did  run prepare.sh but i got
"command not found" (below)
ubuntu@master:~/HiBench/hivebench/bin$ prepare.sh
prepare.sh: command not found
ubuntu@master:~/HiBench/hivebench/bin$

**Comment by adrian-wang** [comment]
You should use 
./prepare.sh
 instead of 
prepare.sh

**Comment by KofDossou** [comment]
ok I got it after i run ./prepare.sh. looks like am getting a new error
ubuntu@master:~/HiBench/hivebench/bin$ ./prepare.sh
========== preparing hive data ==========
/home/ubuntu/HiBench/hivebench/../bin/hibench-config.sh: line 39:
/home/hadoop/b
                           in/hadoop: No such file or directory
/home/ubuntu/HiBench/hivebench/../bin/hibench-config.sh: line 41:
/home/hadoop/b
                           in/hadoop: No such file or directory
/home/ubuntu/HiBench/hivebench/../bin/hibench-config.sh: line 43:
/home/hadoop/b
                           in/hadoop: No such file or directory
JAVA_HOME=/usr/lib/jvm/java-7-oracle
/home/ubuntu/HiBench/hivebench/../bin/hibench-config.sh: line 60:
HADOOP_HOME:
                           /home/ubuntu/hadoop

**Comment by adrian-wang** [comment]
You should set your HADOOP_HOME in hibench-config.sh before run hibench.
For the details, please refer to https://github.com/intel-hadoop/HiBench#getting-started

**Comment by KofDossou** [comment]
After I set my HADOOP_HOME  in hibench-config.sh am still getting error
running ./prepare.sh
ubuntu@master:~/HiBench/hivebench/bin$ ./prepare.sh
========== preparing hive data ==========
/home/ubuntu/HiBench/hivebench/../bin/hibench-config.sh: line 39: version:
command not found
/home/ubuntu/HiBench/hivebench/../bin/hibench-config.sh: line 41: version:
command not found
/home/ubuntu/HiBench/hivebench/../bin/hibench-config.sh: line 43: version:
command not found
JAVA_HOME=/usr/lib/jvm/java-7-oracle
HADOOP_PREFIX=/home/ubuntu/hadoop
/home/ubuntu/HiBench/hivebench/../bin/hibench-config.sh: line 61:
HADOOP_EXECUTABLE: HADOOP_PREFIX/bin
ubuntu@master:~/HiBench/hivebench/bin$

****below is how i set my paths in
home/ubuntu/HiBench/bin/hibench-config.sh**

echo JAVA_HOME=${JAVA_HOME:?/usr/lib/jvm/java-7-oracle}
echo HADOOP_PREFIX=${HADOOP_PREFIX:?/home/ubuntu/hadoop}
echo HADOOP_EXECUTABLE=${HADOOP_EXECUTABLE:?HADOOP_PREFIX/bin}
echo HADOOP_CONF_DIR=${HADOOP_CONF_DIR:?HADOOP_PREFIX/conf}
echo HADOOP_EXAMPLES_JAR=${HADOOP_EXAMPLES_JAR:?HADOOP_PREFIX}
echo MAPRED_EXECUTABLE=${MAPRED_EXECUTABLE:?/home/ubuntu/hadoop}

**Comment by adrian-wang** [comment]
you are pointing to the wrong HADOOP_EXECUTABLE, this should be at HADOOP_HOME/bin/hadoop

**Comment by KofDossou** [comment]
Sir, Am still getting  new error even after pointing HADOOP_EXECUTABLE
to HADOOP_HOME/bin/hadoop.
Your help is appreciated

ubuntu@master:~/HiBench/hivebench/bin$ ./prepare.sh
========== preparing hive data ==========
/home/ubuntu/HiBench/hivebench/../bin/hibench-config.sh: line 39:
HADOOP_HOME: command not found
/home/ubuntu/HiBench/hivebench/../bin/hibench-config.sh: line 41:
HADOOP_HOME: command not found
/home/ubuntu/HiBench/hivebench/../bin/hibench-config.sh: line 43:
HADOOP_HOME: command not found
JAVA_HOME=/usr/lib/jvm/java-7-oracle
HADOOP_HOME=home/ubuntu/hadoop
HADOOP_EXECUTABLE=HADOOP_HOME/bin/hadoop
HADOOP_CONF=HADOOP_HOME/conf/hadoop
HADOOP_EXAMPLES=HADOOP_HOME/conf/hadoop
MAPRED_EXECUTABLE=HADOOP_HOME/conf/hadoop
./prepare.sh: line 46: HADOOP_HOME: command not found
ubuntu@master:~/HiBench/hivebench/bin$

**Comment by adrian-wang** [comment]
You have to set HADOOP_HOME first...

**Comment by KofDossou** [comment]
Sir honestly speaking  i followed your instruction in your previous e-mail
and set path but am still getting error. Looks like
*home/ubuntu/hadoop/bin/hadoop* does not exit but in
*home/ubuntu/hadoop/bin* i see a file called hadoop in there so am lost as
to why its saying no such file or directory?Your continuous help is
appreciated.
ubuntu@master:~/HiBench/hivebench/bin$ ./prepare.sh
========== preparing hive data ==========
/home/ubuntu/HiBench/hivebench/../bin/hibench-config.sh: line 40:
home/ubuntu/hadoop/bin/hadoop: No such file or directory
/home/ubuntu/HiBench/hivebench/../bin/hibench-config.sh: line 42:
home/ubuntu/hadoop/bin/hadoop: No such file or directory
/home/ubuntu/HiBench/hivebench/../bin/hibench-config.sh: line 44:
home/ubuntu/hadoop/bin/hadoop: No such file or directory
JAVA_HOME=/usr/lib/jvm/java-7-oracle
HADOOP_HOME=home/ubuntu/hadoop
HADOOP_EXECUTABLE=home/ubuntu/hadoop/bin/hadoop
HADOOP_CONF=home/ubuntu/hadoop/conf
HADOOP_EXAMPLES=home/ubuntu/hadoop/hadoop-examples*.jar
MAPRED_EXECUTABLE=home/ubuntu/hadoop/bin/hadoop # using hadoop-1 so i set
it same as HADOOP_EXECUTABLE
./prepare.sh: line 46: home/ubuntu/hadoop/bin/hadoop: No such file or
directory
ubuntu@master:~/HiBench/hivebench/bin$

**Comment by adrian-wang** [comment]
oh, I missed a slash there, sorry.
export HADOOP_HOME=/home/ubuntu/hadoop

**Comment by KofDossou** [comment]
works now but after running ./prepare.sh and then ./run-aggregation.sh.i
get some error from hive bin but then i received a success  from
dependencies when i runed mvn process-sources earlier
========== running hive-aggregate bench ==========
Warning: $HADOOP_HOME is deprecated.

Warning: $HADOOP_HOME is deprecated.

Warning: $HADOOP_HOME is deprecated.

JAVA_HOME=/usr/lib/jvm/java-7-oracle
HADOOP_HOME=/home/ubuntu/hadoop
HADOOP_EXECUTABLE=/home/ubuntu/hadoop/bin/hadoop
HADOOP_CONF=/home/ubuntu/hadoop/conf
HADOOP_EXAMPLES=/home/ubuntu/hadoop/hadoop-examples*.jar
MAPRED_EXECUTABLE=/home/ubuntu/hadoop/bin/hadoop
Error: The hive bin file hasn't be downloaded by maven, please check!
ubuntu@master:~/HiBench/hivebench/bin$ ./run-aggregation.sh
========== running hive-aggregate bench ==========
Warning: $HADOOP_HOME is deprecated.

Warning: $HADOOP_HOME is deprecated.

Warning: $HADOOP_HOME is deprecated.

JAVA_HOME=/usr/lib/jvm/java-7-oracle
HADOOP_HOME=/home/ubuntu/hadoop
HADOOP_EXECUTABLE=/home/ubuntu/hadoop/bin/hadoop
HADOOP_CONF=/home/ubuntu/hadoop/conf
HADOOP_EXAMPLES=/home/ubuntu/hadoop/hadoop-examples*.jar
MAPRED_EXECUTABLE=/home/ubuntu/hadoop/bin/hadoop
Error: The hive bin file hasn't be downloaded by maven, please check!

**Comment by adrian-wang** [comment]
@qiansl127 Can you take a look?

**Comment by qiansl127** [comment]
Please check if `HiBench/common/hibench/hivebench/target/hive-0.12.0-bin.tar.gz` exists. After the success of  `mvn process-sources`, the tar file should already be downloaded.

**Comment by KofDossou** [comment]
I have a working hive on my cluster that I use regularly but locating to .
HiBench/common/hibench/hivebench/target. I find a single hive file which
contains(below):
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<html>
 <head>
  <title>Index of /apache/hive</title>
 </head>
 <body>
<h1>Index of /apache/hive</h1>
<pre><img src="/icons/blank.gif" alt="Icon "> <a href="?C=N;O=D">Name</a>
                 <a href="?C=M;O=A">Last modified</a>      <a
href="?C=S;O=A">Size</a>  <a href="?C=D;O=A">Description</a><hr><img
src="/icons/back.gif" alt="[DIR]"> <a href="/apache/">Parent Directory</a>
                            -
<img src="/icons/folder.gif" alt="[DIR]"> <a
href="hive-0.13.1/">hive-0.13.1/</a>            30-Oct-2014 19:44    -
<img src="/icons/folder.gif" alt="[DIR]"> <a
href="hive-0.14.0/">hive-0.14.0/</a>            12-Nov-2014 16:21    -
<img src="/icons/folder.gif" alt="[DIR]"> <a href="stable/">stable/</a>

**Comment by qiansl127** [comment]
If you want to use your own hive bin, you can modify `$HIVE_HOME` and `$HIVE_RELEASE` in `HiBench/bin/hibench-config.sh`

**Comment by KofDossou** [comment]
Should my HIVE_RELEASE be set to my Hive path which is /home/ubuntu/hive?
Am using hive 0.9.0 in my cluster.Upon downloading hive a couple of months
back i moved hive-0.9.0-bin to hive in unix. Should i then modify HIVE_HOME
and HIVE_RELEASE like so (below)
if [ -z "$HIVE_HOME" ]; then
    export HIVE_HOME=hive-0.9.0-bin
    export HIVE_HOME=${DEPENDENCY_DIR}/hivebench/target/${home/ubuntu/hive}

**Comment by KofDossou** [comment]
Am still getting the same error I think am not setting the path to Hive
right?

JAVA_HOME=/usr/lib/jvm/java-7-oracle
HADOOP_HOME=/home/ubuntu/hadoop
HADOOP_EXECUTABLE=/home/ubuntu/hadoop/bin/hadoop
HADOOP_CONF=/home/ubuntu/hadoop/conf
HADOOP_EXAMPLES=/home/ubuntu/hadoop/hadoop-examples*.jar
MAPRED_EXECUTABLE=/home/ubuntu/hadoop/bin/hadoop
Error: The hive bin file hasn't be downloaded by maven, please check!

**hivebench.config.sh
[ -z "$HIVE_HOME" ]; then
    export HIVE_HOME=/home/ubuntu/hive
    export HIVE_HOME=${DEPENDENCY_DIR}/hivebench/target/${HIVE_HOME}
fi

**Comment by KofDossou** [comment]
@qiansl127 <https://github.com/qiansl127>
*@adrian-wang*

Hello Qian and Wang,
                             this is my hive configuration in my
 bashrc(below) it will be nice to know how i can infuse this configuration
into $HIVE_HOME and $HIVE_RELEASE in HiBench/bin/hibench-config.sh. the
hive in bashrc the one i use for hive computation. Your prompt reply is
appreciated  to enable me complete this research that am doing at the
graduate level.
#hive environment Varaibles
export HIVE_CONF=/home/ubuntu/hive/conf
export HIVE_PREFIX=/home/ubuntu/hive
export PATH=$PATH:$HIVE_PREFIX/bin

**Comment by adrian-wang** [comment]
Can you use HIVE_HOME instead of HIVE_PREFIX?

**Comment by KofDossou** [comment]
oh yeah i changed it back to HIVE_HOME and still error exit. i think the
problem is  changing  $HIVE_HOME and $HIVE_RELEASE in
HiBench/bin/hibench-config.sh
as Neo said . In my previous email I made some assumption in HiBench/bin/
hibench-config.sh as how i feel it should look but still was getting the
same error?

**Comment by adrian-wang** [comment]
You should set HIVE_HOME in hibench-config.sh, instead of your bashrc.

**Comment by KofDossou** [comment]
This is how I set it in hivebench.config.sh (below). The bashrc i showed
is an already installed hive i have which I changed the hive_prefix to
hive_home
[ -z "$HIVE_HOME" ]; then
    export HIVE_HOME=/home/ubuntu/hive
    export HIVE_HOME=${DEPENDENCY_DIR}/hivebench/target/${HIVE_HOME}

**Comment by adrian-wang** [comment]
I think you need to remove 
export HIVE_HOME=${DEPENDENCY_DIR}/hivebench/target/${HIVE_HOME}
This aims to find the hive that maven downloaded previously. If you want to use your own hive, you shouldn't include that line.

**Comment by KofDossou** [comment]
Ok I did that . After I removed export
HIVE_HOME=${DEPENDENCY_DIR}/hivebench/target/${HIVE_HOME}.
I was getting the same error so i went ahead to re-run  mvn process-sources so
i can get the dependencies but i got an error .error(below) thanks.
ubuntu@master:~/HiBench/common/hibench$ mvn process-sources -e
[INFO] Error stacktraces are turned on.
[INFO] Scanning for projects...
[ERROR] The build could not read 1 project -> [Help 1]
org.apache.maven.project.ProjectBuildingException: Some problems were
encountered while processing the POMs:
[ERROR] Child module /home/ubuntu/HiBench/common/hibench/hivebench/pom.xml
of /home/ubuntu/HiBench/common/hibench/pom.xml does not exist @

        at
org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:363)
        at
org.apache.maven.DefaultMaven.collectProjects(DefaultMaven.java:636)
        at
org.apache.maven.DefaultMaven.getProjectsForMavenReactor(DefaultMaven
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:234)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.
        at
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
        at java.lang.reflect.Method.invoke(Method.java:606)
        at
org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Laun
        at
org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.jav
        at
org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(La
        at
org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:
[ERROR]
[ERROR]   The project com.intel.hibench:hibench:4.0-SNAPSHOT
(/home/ubuntu/HiBen
[ERROR]     Child module
/home/ubuntu/HiBench/common/hibench/hivebench/pom.xml o
[ERROR]
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions,
please rea
[ERROR] [Help 1]
http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildin
ubuntu@master:~/HiBench/common/hibench$ mvn process-sources
[INFO] Scanning for projects...
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project com.intel.hibench:hibench:4.0-SNAPSHOT
(/home/ubuntu/HiBen
                               ch/common/hibench/pom.xml) has 1 error
[ERROR]     Child module
/home/ubuntu/HiBench/common/hibench/hivebench/pom.xml o
                                                                   f
/home/ubuntu/HiBench/common/hibench/pom.xml does not exist
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e
swit
                 ch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions,
please rea
                       d the following articles:
[ERROR] [Help 1]
http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildin

 gException
u

**Comment by KofDossou** [comment]
This is what I changed in *
/home/ubuntu/HiBench/common/**hibench/pom.xml *based
on error in previous email.I tried to set repo to my hive location.
<properties>.
    
    <repo>http://mirrors.ibiblio.org</repo>
    <file>apache/home/ubuntu/hive/bin</file>
  </properties>

**Comment by adrian-wang** [comment]
If you decide to use your own hive, then leave the mvn command, that is meant to download a hive and some other dependencies for other workloads.
For hivebench, just make sure everything is configured right and then start your workload.

**Comment by KofDossou** [comment]
I run ./run-aggregation.sh and had an output but how do I make sense of
 what has been generated (see below please) to incorporate into my working
paper.I understand from the output that it took 1 mapper and 1 reducer to
complete a job using CPU  time of 2.0sec and time of 0.333 is that correct?

ubuntu@master:~/HiBench/hivebench/bin$ ./run-aggregation.sh
========== running hive-aggregate bench ==========
Warning: $HADOOP_HOME is deprecated.

Warning: $HADOOP_HOME is deprecated.

Warning: $HADOOP_HOME is deprecated.

JAVA_HOME=/usr/lib/jvm/java-7-oracle
HADOOP_HOME=/home/ubuntu/hadoop
HADOOP_EXECUTABLE=/home/ubuntu/hadoop/bin/hadoop
HADOOP_CONF=/home/ubuntu/hadoop/conf
HADOOP_EXAMPLES=/home/ubuntu/hadoop/hadoop-examples*.jar
MAPRED_EXECUTABLE=/home/ubuntu/hadoop/bin/hadoop
Warning: $HADOOP_HOME is deprecated.

rm: cannot remove -r: No such file or directory.
rm: cannot remove -skipTrash: No such file or directory.
rm: cannot remove /user/hive/warehouse/uservisits_aggre: No such file or
directo
                   ry.
WARNING: org.apache.hadoop.metrics.jvm.EventCounter is deprecated. Please
use or
                   g.apache.hadoop.log.metrics.EventCounter in all the
log4j.properties files.
Logging initialized using configuration in
jar:file:/home/ubuntu/hive/lib/hive-c

 ommon-0.9.0.jar!/hive-log4j.properties
Hive history file=/tmp/ubuntu/hive_job_log_ubuntu_201501202005_582129071.txt
OK
Time taken: 6.149 seconds
OK
Time taken: 1.273 seconds
OK
Time taken: 0.018 seconds
OK
Time taken: 0.325 seconds
OK
Time taken: 0.033 seconds
Total MapReduce jobs = 1
Launching Job 1 out of 1
Number of reduce tasks not specified. Estimated from input data size: 1
In order to change the average load for a reducer (in bytes):
  set hive.exec.reducers.bytes.per.reducer=<number>
In order to limit the maximum number of reducers:
  set hive.exec.reducers.max=<number>
In order to set a constant number of reducers:
  set mapred.reduce.tasks=<number>
Starting Job = job_201412202223_0080, Tracking URL =
http://master:50030/jobdetails.jsp?jobid=job_201412202223_0080
Kill Command = /home/ubuntu/hadoop/libexec/../bin/hadoop job
 -Dmapred.job.tracker=hdfs://master:8021 -kill job_201412202223_0080
Hadoop job information for Stage-1: number of mappers: 1; number of
reducers: 1
2015-01-20 20:05:31,335 Stage-1 map = 0%,  reduce = 0%
2015-01-20 20:05:34,351 Stage-1 map = 100%,  reduce = 0%, Cumulative CPU
0.86 sec
2015-01-20 20:05:35,356 Stage-1 map = 100%,  reduce = 0%, Cumulative CPU
0.86 sec
2015-01-20 20:05:36,360 Stage-1 map = 100%,  reduce = 0%, Cumulative CPU
0.86 sec
2015-01-20 20:05:37,365 Stage-1 map = 100%,  reduce = 0%, Cumulative CPU
0.86 sec
2015-01-20 20:05:38,369 Stage-1 map = 100%,  reduce = 0%, Cumulative CPU
0.86 sec
2015-01-20 20:05:39,373 Stage-1 map = 100%,  reduce = 0%, Cumulative CPU
0.86 sec
2015-01-20 20:05:40,377 Stage-1 map = 100%,  reduce = 0%, Cumulative CPU
0.86 sec
2015-01-20 20:05:41,382 Stage-1 map = 100%,  reduce = 0%, Cumulative CPU
0.86 sec
2015-01-20 20:05:42,387 Stage-1 map = 100%,  reduce = 0%, Cumulative CPU
0.86 sec
2015-01-20 20:05:43,402 Stage-1 map = 100%,  reduce = 100%, Cumulative CPU
2.0 sec
2015-01-20 20:05:44,405 Stage-1 map = 100%,  reduce = 100%, Cumulative CPU
2.0 sec
2015-01-20 20:05:45,410 Stage-1 map = 100%,  reduce = 100%, Cumulative CPU
2.0 sec
2015-01-20 20:05:46,421 Stage-1 map = 100%,  reduce = 100%, Cumulative CPU
2.0 sec
MapReduce Total cumulative CPU time: 2 seconds 0 msec
Ended Job = job_201412202223_0080
Loading data to table default.uservisits_aggre
Deleted hdfs://master:8020/user/hive/warehouse/uservisits_aggre
MapReduce Jobs Launched:
Job 0: Map: 1  Reduce: 1   Cumulative CPU: 2.0 sec   HDFS Read: 524 HDFS
Write: 130 SUCCESS
Total MapReduce CPU Time Spent: 2 seconds 0 msec
OK
Time taken: 20.62 seconds
(standard_in) 1: syntax error
Warning: $HADOOP_HOME is deprecated.

(standard_in) 1: syntax error
Warning: $HADOOP_HOME is deprecated.

rm: cannot remove -r: No such file or directory.
rm: cannot remove -skipTrash: No such file or directory.
rm: cannot remove /HiBench/Hive/Output-comp/uservisits_aggre: No such file
or directory.
Warning: $HADOOP_HOME is deprecated.

Warning: $HADOOP_HOME is deprecated.

**Comment by adrian-wang** [comment]
did you run prepare before you run aggregation?

**Comment by adrian-wang** [comment]
Is there any update?

**Comment by KofDossou** [comment]
Everything is working great. Upon configuring additional nodes of 4 - 16
(for the time being), I see the time change from 0.0034sec for a 4 node to
0.049sec for a 16 node run-join workload and for a run-aggregation 4node
(0.03sec) - 16node (0.05).Also the total CPU time changed immensely across
various number of nodes with 16 node having the highest for a run-join
workload of 12sec720msec though other nodes shows a decrease in CPU time
that is 4node(17sec 520msec), 8 node(7sec 250msec),12 node (1sec
670msec).I'll be happy to email you the outputs of each workload for your
input as well. I  was expecting  a time decrease as I added more nodes but
that has been conflicting since(4 node) has lower time than a 16 node. Your
take on this please

**Comment by adrian-wang** [comment]
If the data set is not so large but you force it to run on a large cluster, there would be too much networking and IO consuming. Since the origin issue is gone, I am going to close this one.
Thanks for your feedback, and your interest in HiBench!

**Comment by attu-mittu** [comment]
[INFO] Reactor Summary:
[INFO] 
[INFO] hibench ........................................... SUCCESS [0.939s]
[INFO] nutchindexing ..................................... SUCCESS [12.502s]
[INFO] mahout ............................................ SUCCESS [15.796s]
[INFO] hivebench ......................................... SUCCESS [4.656s]
[INFO] Sparkbench ........................................ SUCCESS [50.538s]
[INFO] PEGASUS: A Peta-Scale Graph Mining System ......... SUCCESS [4.649s]
[INFO] HiBench data generation tools ..................... SUCCESS [14.058s]
[INFO] Streamingbench .................................... SUCCESS [0.012s]
[INFO] Streamingbench data generation tools .............. SUCCESS [11.365s]
[INFO] Streaming Benchmark Zookeeper Helper Utils ........ SUCCESS [9.765s]
[INFO] Streaming Benchmark Spark ......................... SUCCESS [44.975s]
[INFO] Streaming Benchmark Storm ......................... FAILURE [1.745s]
[INFO] Streaming Benchmark Samza ......................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2:53.167s
[INFO] Finished at: Sun Nov 22 11:15:21 IST 2015
[INFO] Final Memory: 73M/288M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.thrift.tools:maven-thrift-plugin:0.1.11:compile (thrift-sources) on project streaming-bench-storm: thrift did not exit cleanly. Review output for more information. -> [Help 1]


How to solve this?? Please give your valuable suggession........

**Comment by carsonwang** [comment]
@attu-mittu , please open a new issue for any issue you encounter next time.
Please refer to https://github.com/intel-hadoop/HiBench/issues/147 to resolve your problem.

**Comment by attu-mittu** [comment]
okay thank you. :)
