### ISSUE TITLE
Hivebench: how to generate data without compression

### ISSUE THREAD

**Issue by AnjaGer** [intel-hadoop/HiBench#76]
I generate data for the hivebench:

cd ~/HiBench-master/hivebench
bin/prepare.sh

I would like to have the data without compression.
The generated data are compressed, 
whether COMPRESS_GLOBAL in bin/hibench-config.sh is set to 0 or 1.

hdfs dfs -text /user/hanalite/hibench/Hive/Input/rankings/part-00000 | head
15/01/29 10:56:31 INFO zlib.ZlibFactory: Successfully loaded & initialized native-zlib library
15/01/29 10:56:31 INFO compress.CodecPool: Got brand-new decompressor [.deflate]
15/01/29 10:56:31 INFO compress.CodecPool: Got brand-new decompressor [.deflate]
15/01/29 10:56:31 INFO compress.CodecPool: Got brand-new decompressor [.deflate]
15/01/29 10:56:31 INFO compress.CodecPool: Got brand-new decompressor [.deflate]
0       nbizrgdziebsaecsecujfjcqtvnpcnxxwiopmddorcxnlijdizgoi,65738,16
48      czoqdnkqnonnkmjlzfsntboumupseoahz,9451,29
96      jxgpkxbhomwgxrjpqdn,6678,20

Any tip for me?

**Comment by adrian-wang** [comment]
If you set COMPRESS_GLOBAL to 0, the data generated should not be compressed.
