### ISSUE TITLE
Paths in bin/functions/load-config.py are hard-coded

### ISSUE THREAD

**Issue by AnjaGer** [intel-hadoop/HiBench#99]
Hi,
when I run workload/pagerank/prepare/prepare.sh, I get this error:
This filename pattern "/usr/hdp/2.2.4.2-2/hadoop//share/hadoop/mapreduce/hadoop-mapreduce-examples-*.jar" is required to match only one file.
However, there's no file found, please fix it.

The path name is concatenate in bin/functions/load-config.py line 269:
HibenchConf["hibench.hadoop.examples.jar"] = OneAndOnlyOneFile(HibenchConf['hibench.hadoop.home'] + "/share/hadoop/mapreduce/hadoop-mapreduce-examples-*.jar")

It would be nice if the second part of the path could be set via variables, too

**Comment by lvsoft** [comment]
You can set `hibench.hadoop.examples.jar` in your configuration explicitly to bypass this auto probe step. Auto probe will only work for default installation of Hadoop/Spark, which is used to cover 99% common cases.
